### ISSUE TITLE
Short command line options issues

### ISSUE THREAD

**Issue by mnojek** [MarketSquare/robotframework-tidy#104]
You recently added short version `-l` for `--list-transformers` which is already used for `--lineseparator`. When calling `robotidy -l` it actually shows output from `--list-transformers` so I'm not sure if it's only a documentation problem.

Another thing is the lack of short version for help message. I suggest adding `-h` in addition to already existing `--help`.

Also `--verbose` option does not have a definition and I think it could be listed closer to the bottom of the help message.

**Comment by bhirsz** [comment]
Commands are evaluated in order so duplicated command name (-l) happened to match --list-transformers. --lineseparator stopped working.

I will add ``-h`` short version and imrpove ``--verbose`` description 👍
