### ISSUE TITLE
consistent naming for AssignmentNormalizer

### ISSUE THREAD

**Issue by adrszad** [MarketSquare/robotframework-tidy#115]
to be consistent with other transformers names it could be named 'NormalizeAssignments'

**Comment by bhirsz** [comment]
I agree. It's not backward compatible change but it's good time for this change before robot.tidy is officially deprecated. I will rename it and add old name to upcoming 'naming suggester' (it will print out the correct name if you provide wrong one, see #107. It also supports printing all transformer names with 'Normalize' in name if you just run robotidy --transform Normalize).
