### ISSUE TITLE
option for NormalizeSeparators to discard particular sections

### ISSUE THREAD

**Issue by adrszad** [MarketSquare/robotframework-tidy#116]
let's say I have Settings and Variables sections already aligned by other transformers, then running NormalizeSeparators transformer breaks that previous alignment.
It affects me especially when having pre-commit hook with seperate hooks per transformer, there is an infinite loop of refactors done by these transformers and there's no way to commit without '--no-verify' option.

**Comment by bhirsz** [comment]
Are you able to use NormalizeSeparators first then other transformers? Whatever NormalizeSeparator would break it would be then 'fixed' by other transformers. Normally when you run 'robotidy src' NormalzieSeparator always run first so there is no issue.

But I will add option, ie ``sections=testcases,keywords`` so the transformer will only parse those sections and leave rest.
