### ISSUE TITLE
handling comments for OrderSettings transformer

### ISSUE THREAD

**Issue by adrszad** [MarketSquare/robotframework-tidy#118]
Having this code:
```
Some Keyword
    Another Keyword
    [Teardown]   Run Keywords   Teardown Keyword 1 
    ...     Teardown Keyword 2 
#  ...     Teardown Keyword 3
```

it's being transformed to:
```
Some Keyword
    Another Keyword
#  ...     Teardown Keyword 3
    [Teardown]   Run Keywords   Teardown Keyword 1 
    ...     Teardown Keyword 2 
```
It may be lead to some issues in the future when someone uncomments it.
It might be good to preserve this comments order somehow, but I'm not sure if it should be a parameter or done always.

another case:
```
Some Keyword
    ${var}=   Another Keyword
    [Return]   ${var}

#OTHER KEYWORDS
Other Keyword
    Some Other Keyword
```
is transformed to:
```
Some Keyword
    ${var}=   Another Keyword

#OTHER KEYWORDS
    [Return]   ${var}
Other Keyword
    Some Other Keyword
```

**Comment by bhirsz** [comment]
I was aware of the other case - everything between keyword/test case is considered as part of the body. That's why putting [Return] /[Teardown] at the end of body leads to this. For second case I can modify the code so it would consider end of keyword where the last data (non empty line / comment) statement is. 

It should also take care of the first case - but I will test it.

**Comment by bhirsz** [comment]
Resolved in linked PR. The only time the comments will not be handled properly is when [Return] or [Teardown] are actually in wrong order:
```
Return first and comment last
    [Return]  stuff
    Keyword
    # I want to be here

# what will happend with me?
```
[Return] will move after last data like statement
```
Return first and comment last
    Keyword
    [Return]  stuff
    # I want to be here

# what will happend with me?
```
Other cases mentioned by your are resolved correctly.
```
