### ISSUE TITLE
Transformer: Make '=' equal sign usage consistent

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-tidy#13]
Those lines are identical:
```
${var}    Set Variable
${var}=    Set Variable
${var} =  Set Variable
```

Whenever we're using `=` it should be consistent. By default we can remove all of them but give configurable option to to use them (with extra space or not before `=`).

**Comment by pekkaklarck** [comment]
You can also use `=` in the Variables section. It's lot quite rare, though, and probably shouldn't be configured with the same option used for configuring `=` in assignments elsewhere.

**Comment by mnojek** [comment]
> You can also use `=` in the Variables section. It's lot quite rare, though, and probably shouldn't be configured with the same option used for configuring `=` in assignments elsewhere.

Wow, I didn't even know that 😀
