### ISSUE TITLE
`robotidy --list` doesn't list all supported transformers

### ISSUE THREAD

**Issue by dcrblack** [MarketSquare/robotframework-tidy#137]
Calling `robotidy --list` returns the following for version 1.2.0:

```
Run --desc <transformer_name> to get more details. Transformers:
NormalizeSeparators
DiscardEmptySections
MergeAndOrderSections
RemoveEmptySettings
AssignmentNormalizer
OrderSettings
OrderSettingsSection
AlignSettingsSection
AlignVariablesSection
NormalizeNewLines
NormalizeSectionHeaderName
NormalizeSettingName
ReplaceRunKeywordIf
SplitTooLongLine
```

This list doesn't include the `SmartSortKeywords` transformer.
It would also be good if this list is sorted before it is returned.

**Comment by bhirsz** [comment]
Thanks for your report, it's already fixed in https://github.com/MarketSquare/robotframework-tidy/issues/114 and it will be released in 1.3.0 - I will check if I can release it soon since we have few upcoming changes and I don't want people to trip over issues that are already fixed ;)
