### ISSUE TITLE
[Bug] ReplaceRunKeywordIf transformer issue when returning a value

### ISSUE THREAD

**Issue by adrszad** [MarketSquare/robotframework-tidy#140]
There is an issue in case when  Run Keyword If  statement was returning some value to variable and the if condition was not met. The variable was not found but after ReplaceRunKeywordIf it's not found. See the following cases:
![image](https://user-images.githubusercontent.com/17517440/123918789-811cf080-d984-11eb-988d-2214fbca7a09.png)
and this log:
![image](https://user-images.githubusercontent.com/17517440/123918865-985bde00-d984-11eb-9394-a30b080d37ea.png)

test2 is code before robotidy
test3 is code after robotidy
test4 is the code fixed by initializing variable as none.

**Comment by bhirsz** [comment]
Yes, by default run keyword if sets all variables to none if condition is not met. We should add ELSE clause that will perform this operation instead.
