### ISSUE TITLE
`robotidy --list` should return transformers in order

### ISSUE THREAD

**Issue by dcrblack** [MarketSquare/robotframework-tidy#141]
Calling `robotidy --list` returns the following for version 1.2.0:

```
NormalizeSeparators
DiscardEmptySections
MergeAndOrderSections
RemoveEmptySettings
AssignmentNormalizer
OrderSettings
OrderSettingsSection
AlignSettingsSection
AlignVariablesSection
NormalizeNewLines
NormalizeSectionHeaderName
NormalizeSettingName
ReplaceRunKeywordIf
SplitTooLongLine
```

Would be nice to return this list in order like so:

```
AlignSettingsSection
AlignVariablesSection
AssignmentNormalizer
DiscardEmptySections
MergeAndOrderSections
NormalizeNewLines
NormalizeSectionHeaderName
NormalizeSeparators
NormalizeSettingName
OrderSettings
OrderSettingsSection
RemoveEmptySettings
ReplaceRunKeywordIf
```

Makes it easier to find transformers you're looking for and it matches the order that is listed in the docs: https://robotidy.readthedocs.io/en/latest/transformers/index.html#

**Comment by bhirsz** [comment]
``--list`` return transformers in the order of transforming (so for example file is first transformerd by NormalizeSeparators, then DiscardEmptySections..). But I agree that's not intuitive and it doesn't match order from the docs. I can change the order to be alphabetical.

**Comment by bhirsz** [comment]
Implemented in linked PR. Turns out I've discovered that Robotidy does not always use the same order (order could be overriden by --transformer options) and it was not intended by default -> I've fixed that too.
