### ISSUE TITLE
When using --diff option, it prints empty line for eac file in the console

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-tidy#160]
When I run robottidy with `robotidy --diff path/to/folder` and folder contains many robot files, then tidy will print empty line in the console for each file in the folder. 

Example, I get
```
 ~/w/robotframework-playwright (robot_tidy)> robotidy --diff path/to/folder
 
 
 
 
 
 ~/w/robotframework-playwright (robot_tidy)> 
 ```
 
 But I did expect to get 
```
 ~/w/robotframework-playwright (robot_tidy)> robotidy --diff path/to/folder 
 ~/w/robotframework-playwright (robot_tidy)> 
 ```

**Comment by bhirsz** [comment]
Thank you for the report - I can confirm this issue and I will fix it.
