### ISSUE TITLE
lineseparator option is not respected

### ISSUE THREAD

**Issue by fdaguin** [MarketSquare/robotframework-tidy#163]
**Describe the problem**
When using the `lineseparator` option, either with..

```toml
[tool.robotidy]
lineseparator = "unix|windows|native"
```

..or `--lineseparator unix|windows|native`, the option value is not respected.

**To Reproduce**
1. Create a `.robot` file with a reference EOL, let's say `CRLF`
2. Use robotidy with `overwrite=true` and with a different EOL target, in this case `lineseparator=unix`

The file will still have `CRLF` instead of `LF`.

**Expected behavior**
Based on the `lineseparator` value, EOL are correctly applied.

**Environment**
 - OS: Windows
 - Tidy version: 1.4.0
 - Python version: 3.9.6
 - Installation method: pip+pypi

**Comment by bhirsz** [comment]
Thank you for report, I can confirm it. It does originate from the way Python behaves with new endings when saving the file to the disk - it does replace it for native ending. But there is newline option to workaround it - I will fix the issue (and add some tests as it looks this option was pretty much ignored in testing).

**Comment by fdaguin** [comment]
Thank you @bhirsz ! 😃
