### ISSUE TITLE
Is there a way to exclude a transform?

### ISSUE THREAD

**Issue by neophiliac** [MarketSquare/robotframework-tidy#164]
My Library and Resource statements must be in a certain order, and tidy "fixes" that order and breaks my tests. Is there a way to exclude (temporarily disable?) a transform?

If not, please consider this a feature request.

**Comment by bhirsz** [comment]
It's either "selected ones" or "all". In that case you would need to list all transformers except the one that you dont want to with --transform. I know that its not that convenient so I'll acknowledge your feature request and I will add way to run all but disable selected.
But that would disable transformer for whole run.  If you need to disable it just for one file we would need yet another new feature. It would be possible for example with introducing "exclude" option with the option to list transformers (ie ```--exclude file:transformerName```. But I need to think what would be best in this situation

**Comment by bhirsz** [comment]
Additionaly someone else also complained that ``OrderSettingsSection`` breaks their Robot execution - after reordering the imports (where some variables imports should be before given resource/library file). I have propose to disable ordering the imports by default - it can be enabled through cli. Would it be fine workaround for now? 

The ``OrderSettingsSection`` is doing other usefull things so I it would be shame to lose it all by disabling it whole. For example with ordering imports disabled by default we could still transform this:
```
Metadata  value  param
Library  Stuff
Force Tags  tag
...  tag

Documentation  doc  # this is comment
...  another line
Test Timeout  1min

# i want to be keep together with Test Setup

Test Setup  Keyword


Suite Setup  Keyword


Variables   variables.py

Library  Collections
Suite Teardown  Keyword2
Resource    robot.resource
Default Tags  1
Library  stuff.py  WITH NAME  alias
```
to this
```
Documentation  doc  # this is comment
...  another line
Metadata  value  param

# imports are not ordered here, they appear in the same order as before - just grouped together
Library  Stuff
Variables   variables.py
Library  Collections
Resource    robot.resource
Library  stuff.py  WITH NAME  alias

Suite Setup  Keyword
Suite Teardown  Keyword2
# i want to be keep together with Test Setup
Test Setup  Keyword
Test Timeout  1min

Force Tags  tag
...  tag
Default Tags  1
```

without losing order of imports.

**Comment by bhirsz** [comment]
I've implemented both features - possibility of disabling just one transformer AND preserving order of imports by default in OrderSettingsSection. Disabling transformers per files is planned for future. Is is enough for you and I can close the issue or you prefer disabling per file?

**Comment by neophiliac** [comment]
Sorry for my slow response; I can't add issues outside my enterprise from my work Github account. 

Preserving the import order is the best solution for my use cases. Thanks for that change!
