### ISSUE TITLE
Preserve order of imports in OrderSettingsSection

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-tidy#167]
Modyfing order of imports can break some of the robot tests - if there are inter dependencies between files. It's better to preserve order of import settings. Other settings can be ordered (and all imports can be grouped together).

**Comment by bhirsz** [comment]
It can work as workaround for #164

**Comment by aaltat** [comment]
I run tidy with two different configurations, because there is dependency also to variable files https://github.com/MarketSquare/robotframework-browser/blob/master/tasks.py#L440

**Comment by bhirsz** [comment]
@aaltat Yeah that's why now robotidy will not order imports. It will group them, ie:
```
Force Tags  tag
Variables  variables.py
Test Timeout  1min
Library  stuff.py
```
to
```
Variables  variables.py
Library  stuff.py

Test Timeout  1min

Force Tags  tag
```
But it will not change order of imports (variables, libraries, resources) itself. You will be able to overwrite this behaviour with supplying your custom order, like you did in your example. It will be also possible to preserve order of any other setting group by supplying 'preserved':
```
robotidy --configure OrderSettingsSection:settings_order=preserved
```
I hope it will help with those issues - user should not be forced to configure anything and still get working tests before and after formatting.

**Comment by aaltat** [comment]
Ah, I see. This was about all imports (resource,  variable,  library), not only library. Then it would solve my problem.
