### ISSUE TITLE
Transformer RenameKeywords Incorrectly convert to lower case  name when Library is first

### ISSUE THREAD

**Issue by IlfirinPL** [MarketSquare/robotframework-tidy#199]
Related to #194 
Transformer RenameKeywords Incorrectly convert to lower case  name when Library is first

For case when ex. Library is first like this case Process.   will incorrectly convert "Run" to "run"
Process.Run Process   ->  Process.run Process 
RPA.Browser.Playwright.Take Screenshot ->    Rpa.browser.playwright.take Screenshot

**Comment by bhirsz** [comment]
Thank you for the report - I was able to reproduce it and also fix locally. I will push fix soon.

**Comment by IlfirinPL** [comment]
There  is case with "RPA" where whole string should stay uppercase. Maybe in future whitelist for substrings

**Comment by IlfirinPL** [comment]
I have similar case for Library name issues
    SeleniumLibrary.Open Browser   ->     Seleniumlibrary.open Browser
    SSHLibrary.Open Connection    host  ->     Sshlibrary.open Connection    host

**Comment by bhirsz** [comment]
I think I will just ignore library part - so only keyword part (after last '.') is capitalized. For example:
RPA.keyword -> RPA.Keyword

But

Rpa.Keyword -> Rpa.Keyword (since we don't change library part).

Then it could be improved in the future if we will get module for recognizing libraries from pythonpath.

**Comment by bhirsz** [comment]
The alternative is that I can try to at least title case every part of the name:

RPA.Browser.playwright.Take Screenshot -> splits into RPA, Browser, playwright, Take Screenshot. playwright -> Playwright and rest stays without change.

**Comment by IlfirinPL** [comment]
I think is nice solution for now, but i future i see other cases in some keywords project will use some abbreviations.
example  
Connect To System ABC
Create Product DFG

where ABC and DFG are part that should stay  uppercase

This make it a little more complex.  
And Libraries names will be included as default

**Comment by bhirsz** [comment]
I've reworked it a bit to just uppercase first letter of every words, so parts like ABC stays ABC (and not Abc).

**Comment by IlfirinPL** [comment]
I have tested this version its great way to format old code :)
