### ISSUE TITLE
Support for all robot.tidy features

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-tidy#2]
To be able to deprecate robot.tidy all or most features of robot.tidy should be covered by new external tool Tidy. We should list what are the features (together with possible configuration/how it behaves) and migrate them to new tool.

**Comment by bhirsz** [comment]
Currently supported by robot.tidy:

Cleaner:
* section headers are normalized to format `***  Section Name ***`
* setting names are normalize in setting table and in test cases and user keywords to format `Setting Name` or `[Setting Name]`
* settings without values are removed
* Empty lines after section headers and within items are removed
* For loop declaration and end tokens are normalized to `FOR` and `END`
* Old style for loop indent (i.e. a cell with only a `\\`) are removed

NewlineNormalizer:
* ensures that there is one line between sections, test cases and keyword definitions

SeparatorNormalizer:
* normalize separators (spaces to pipes or other way around)
* normalize indents

Aligner:
* it (probably) aligns this:
```
*** Test Case ***  col_name   col_name2
Test Case Name  ${var}         {var2}
```

**Comment by sergii-tsymbal-exa** [comment]
In order to use robotidy as a full replacement for tidy, it would also be good to support tool configuration and output as close to the deprecated tool as possible. This would make the transition easier
I find this config to be as close in 1.4.0 to the original tidy as possible. It would be nice to add it to docs:
```toml
[tool.robotidy]
configure = [
    "MergeAndOrderSections: order = settings,variables,testcases,keywords,comments",
    "OrderSettings: keyword_before = arguments,documentation,tags,timeout",
    "OrderSettingsSection: new_lines_between_groups = 0",
]
```
The biggest difference is currently in AlignSettingsSection and AlignVariablesSection. Tidy uses a min absolute width of 19 chars and does not align wider columns. Supporting such behavior via configuration will help

**Comment by bhirsz** [comment]
> In order to use robotidy as a full replacement for tidy, it would also be good to support tool configuration and output as close to the deprecated tool as possible. This would make the transition easier
> I find this config to be as close in 1.4.0 to the original tidy as possible. It would be nice to add it to docs:
> 
> ```toml
> [tool.robotidy]
> configure = [
>     "MergeAndOrderSections: order = settings,variables,testcases,keywords,comments",
>     "OrderSettings: keyword_before = arguments,documentation,tags,timeout",
>     "OrderSettingsSection: new_lines_between_groups = 0",
> ]
> ```
> 
> The biggest difference is currently in AlignSettingsSection and AlignVariablesSection. Tidy uses a min absolute width of 19 chars and does not align wider columns. Supporting such behavior via configuration will help

I don't know how I missed it - it will be really good addition to docs! I will see what I can do with it so the transition will be smoother.

**Comment by bhirsz** [comment]
Added `Migrating from robot.tidy` containing tips from @sergii-tsymbal-exa section to our docs - it will be generated during next release. I will also update it with information with newly added "min_width" parameters allowing for fixed width of column.
