### ISSUE TITLE
`--lineseparator` option to use whatever separator the file is already using

### ISSUE THREAD

**Issue by DetachHead** [MarketSquare/robotframework-tidy#209]
in my team, some people use git `core.autocrlf=true` and others use `input`, which means `robotidy` will change the line endings unnecessarily. it would be nice if there was an option to make it use whatever line endings the file already has

**Comment by bhirsz** [comment]
Currently we have three (fixed) options: native, windows and linux. To implement your idea we would need to implement some sort of checker for separator type before running transformations (and we could call `--lineseparator detect` or `--lineseparator keep`). Is it what you have in mind?

What if line separator are not consistent? Easiest would be just use the first line separator. We could also try to count and pick most popular one (with small hit to performance but nothing noticeable).

**Comment by DetachHead** [comment]
i'm not sure what the best way is, maybe see how other formatters handle this issue? for example prettier: https://prettier.io/docs/en/options.html#end-of-line

> `"auto"` - Maintain existing line endings (mixed values within one file are normalised by looking at what’s used after the first line)

**Comment by bhirsz** [comment]
"The other are doing this" is deciding factor ;) We can go with 'auto' and just check for first line ending. Basically if linesep is set to auto and we're saving the model to disk here:
https://github.com/MarketSquare/robotframework-tidy/blob/d9a7cd6c26f97a927a8bc9171f04a71202520961/robotidy/app.py#L98
then we could check the source for line endinds and use it instead. Here usage of 'newlines' attribute:
https://stackoverflow.com/questions/2798627/how-can-i-detect-dos-line-breaks-in-a-file

**Comment by bhirsz** [comment]
I can do it - or leave if for you if you want to create PR.

**Comment by DetachHead** [comment]
thanks! sorry i didn't see your comment
