### ISSUE TITLE
[Transformer] NormalizeTags transformer

### ISSUE THREAD

**Issue by adrszad** [MarketSquare/robotframework-tidy#212]
Transformer for cleaning the tags, by converting them to same case and removing duplicates.
What should be the default case and which other cases to support? Lowercase?

This library seems to be handy if we want to support more cases: 
https://pypi.org/project/stringcase/ 

Optional feature:
> With extra option "common_to_force_tags" (temporary name) that would move tags that are repeated in every test case to Force Tags. 
> 
> _Originally posted by @bhirsz in https://github.com/MarketSquare/robotframework-tidy/issues/205#issuecomment-926390647_

**Comment by bhirsz** [comment]
Interesting library - could come in handy with my other normalizers. Although for now we can stick to cases you implemented in PR - with lowercase as default.

Another idea is providing parameter for ignoring (not normalizing) some of the test cases. For example `[A-Z]+-[0-9]+` for skipping 'JIRA-123' tags. But it's idea for the future.

**Comment by bhirsz** [comment]
@adrszad I have merge the code and I will create release tommorow. Do you think we can close this issue? (we can create another one if we want to extend this transformer)

**Comment by adrszad** [comment]
> @adrszad I have merge the code and I will create release tommorow. Do you think we can close this issue? (we can create another one if we want to extend this transformer)

yes, let's do it, I'll try to handle both excluding tags by regex and moving common to force tags
