### ISSUE TITLE
NormalizeSectionHeaderName forces "Tasks" to "Test Cases"

### ISSUE THREAD

**Issue by admorgan** [MarketSquare/robotframework-tidy#218]
I use RF for a lot of automation, and therefore there are a lot of files with *** Tasks *** sections. Throughout the documentation it is mentioned that Tasks can be converted to *** Test Cases *** based on what is found first in the file, but I have found that in a file with only a *** Tasks *** section the NormalizeSectionHeaderName transformation will convert it to *** Test Cases ***

**Comment by bhirsz** [comment]
Fixed both this and other issue that you've opened - I should create release in few days max.
