### ISSUE TITLE
robotidy screws up the syntax in python files

### ISSUE THREAD

**Issue by DetachHead** [MarketSquare/robotframework-tidy#227]
before:
```py
def foo() -> None:
    if True:
        ...
```
command:
```
robotidy main.py
```
after:
```py
def foo() -> None:
    if True:
...
```

i think robotidy should throw an error when you attempt to run it on a python file.

use case: i have vscode configured to run `robotidy` when saving `.robot` files, however there seems to be an issue with the extension i use where it sometimes attempts to run it on the wrong file (https://github.com/Gruntfuggly/triggertaskonsave/issues/24), which means robotidy sometimes incorrectly runs on `.py` files

**Comment by bhirsz** [comment]
Thanks for the report - yeah it's not expected behaviour. You already found the place where robotidy takes care of paths in your attached PR -> we should update logic here so files provided from cli are also checked against our exclude/include options.
