### ISSUE TITLE
Add one line IF support

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-tidy#230]
Robot Framework 5.0 will introduce one liner IFs:

```
IF  ${val}==5  Keyword
```
https://github.com/robotframework/robotframework/issues/4093

ReplaceRunKeywordIf and AddMissingEnd should respect it (and propose shortened version if there is need to transform code). 
We can also add new transformer for shortening the IFs in the code (unless it would take more than some preconfigured `line_length`).

**Comment by mnojek** [comment]
Probably we need a similar issue in Robocop?

**Comment by bhirsz** [comment]
Yes, and more  for 5.0 - since some of the rules should change how they work or we need  some new rules. I believe that "this if could be oneline" logic will be the same for robotidy and robocop. Robotidy will then transform if necessary and robocop report issue
