### ISSUE TITLE
[Enhancement]: Clean unused keywords

### ISSUE THREAD

**Issue by Julien-LM** [MarketSquare/robotframework-tidy#238]
Hi, would it be possible to add a feature to clean unused kw in a RF project? Thanks

**Comment by bhirsz** [comment]
Hello, with the way it currently stands it's not possible with Robotidy. To discover not used keywords we would need to scan whole projects, resolve dynamic scope (such as imports, variables etc). Hovewer discovering not used keywords will be possible in the (close) future with my other tool - I will comment here when it's released. For now I'm closing the issue.
