### ISSUE TITLE
ignore comments

### ISSUE THREAD

**Issue by DetachHead** [MarketSquare/robotframework-tidy#267]
sometimes i want to ignore the changes made by robotidy on a specific line (or range of lines):
![image](https://user-images.githubusercontent.com/57028336/156981643-b43113da-1ddc-4b13-ad36-5b78eb307b98.png)

it would be good if i could do something like
```robot
*** Test Cases ***
iOS smoker  # robotidy:ignore
```

**Comment by bhirsz** [comment]
It's technically possible to implement - it would reuse --startline and --endline logic (+ extra logic required for parsing disablers in comments). 

We can combine syntax from https://stackoverflow.com/questions/58584413/black-formatter-ignore-specific-multi-line-code and above:
```
*** Test Cases ***
iOS smoker  # robotidy: skip  disable only for object in particular line
    Step 1
    Step 2
    # robotidy: on  disable for following lines
    iOS only step
    Weird  spacing     but               ignore       it
    # robotidy: off
```

**Comment by bhirsz** [comment]
It will be easier to implement if it willl only work within one level of indentation ie for given block. And it will be easier to use as well:
```
*** Test Cases ***
Test
    # robotidy: off  off only for  this test even if it will not be set to on after the test

Test 2
    Stuff
    FOR    ${var}   IN  @{LIST}
        Step 2
        # robotidy: off  off for the rest of the loop, but on outsside the loop
    END
    Step 3
```

**Comment by bhirsz** [comment]
Good news - I already implemented the solution. It will use ``robotidy: off`` and ``robotidy: on`` markers and allows to either disable robotidy in span of lines or particular node:

```
*** Test Cases ***
Test
    Keyword
    Keyword
    ...  ${arg}  # robotidy: off - it will disable only for this Keyword

# robotidy: off
Test2
     Step
# robotidy: on  - it will disable for all lines between this mark and previous # robotidy: off
```

I'm still working on tests as it does require quite extensive testing. I will update when the change will be on the main branch.

**Comment by bhirsz** [comment]
The change is in open PR. After it'll be merged it will be in next release - somewhere after the Eastern and before end of next week ;). Just by looking at PR you may guess why it took so much time - 102 files were modified ;) 🔥

**Comment by bhirsz** [comment]
All above feature all implemented. Additionaly it's possible to disable formatting in whole file (by adding ``# robotidy: off`` in first line) and in whole section (by adding disabler comment in section header: ```*** Variables ***  # robotidy: off).
