### ISSUE TITLE
2 newlines added to end of file when it contains test cases & keywords and the keyword ends in a single line `IF` statement

### ISSUE THREAD

**Issue by DetachHead** [MarketSquare/robotframework-tidy#271]
```robot
*** Test Cases ***
foo
    No Operation

*** Keywords ***
Bar
    IF    ${True}    No Operation
```

![image](https://user-images.githubusercontent.com/57028336/159828538-fd2c6600-4b67-4252-bc56-9de82b27e0d3.png)

2.0b1 (b5d815df3bdb8f842c7e94e25ec208fd638f1173)

**Comment by DetachHead** [comment]
`robotidy --check --diff` fails both with and without the second newline

**Comment by bhirsz** [comment]
Hi, thanks for the report. I was planning to do release today but I will try to fix this issue first. I can reproduce it too and it's bit not deterministic (running in loop - if I don't have any lines it will result in 2 empty lines, then in one line, then in two empty lines..). Suprisingly it's not fault of the NormalizeNewLines and InlineIf transformers - I'm investigating the source of the problem.

**Comment by bhirsz** [comment]
Found the problematic transformer - ``MergeAndOrderSections``.
