### ISSUE TITLE
2.1.0 isnt on pypi

### ISSUE THREAD

**Issue by DetachHead** [MarketSquare/robotframework-tidy#278]
https://pypi.org/project/robotframework-tidy/#history

![image](https://user-images.githubusercontent.com/57028336/160503548-ed1a231f-53c7-4b18-9a3d-af87d7a21c11.png)

**Comment by bhirsz** [comment]
Thanks for the noticiting, I have no idea why the workflow didn't trigger - I've started it manually.

**Comment by DetachHead** [comment]
looks like it's published now, thanks!

should i close this issue or did you want to leave it open to investigate why it didn't trigger automatically?

**Comment by bhirsz** [comment]
I will close it
