### ISSUE TITLE
[Transformers] NormalizeNewLines don't remove empty lines in FOR

### ISSUE THREAD

**Issue by IlfirinPL** [MarketSquare/robotframework-tidy#288]
Transformer NormalizeNewLines  is not removing  empty lines that are inside FOR 

configuration for transformer
"NormalizeNewLines:consecutive_lines=0"

Before

    Log To Console    message

    Log To Console    message

    FOR    ${element}    IN    A    B    C
    
        Log    ${element}

        Log    ${element}

    END

Expected After

    Log To Console    message
    Log To Console    message
    FOR    ${element}    IN    A    B    C
        Log    ${element}
        Log    ${element}
    END

**Comment by bhirsz** [comment]
Thanks for the report - I don't know how it was missed (quite big oversight!). It shouldn't be hard to implement since it'll reuse the same logic used for fixing the lines in keyword/test cases.

**Comment by bhirsz** [comment]
Released in Robotidy 2.2.
