### ISSUE TITLE
New transformer to sort import order

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-tidy#289]
Robocop, rule 0911, complains "Builtin library import XXX should be placed before YYY". I like to have a transformer sorting the imports appropriately.

**Comment by bhirsz** [comment]
https://robotidy.readthedocs.io/en/latest/transformers/OrderSettingsSection.html#imports-order


Did you try configuring OrderSettingsSection - does it satisfy this rule? It's not enabled by default because for some people import order needs to be preserved (since one of the sub imports could require your import from the top file - not the best design but it happens).

**Comment by MoreFamed** [comment]
@bhirsz , thanks, I finally managed it, but the documentation confused me vastly. It reads:

_Imports order_

_By default order of imports is preserved. You can overwrite this behaviour:
robotidy --configure OrderSettingsSections:imports_order=library,resource,variables_

_You can also preserve order inside any group by passing preserved instead of setting names:
robotidy --configure OrderSettingsSections:settings_order=preserved_

The first article states: when using the statement, libraries will come first, then resources, and finally variables. But it does not say a word that libraries will be sorted during the process, i.e. their _mutual order_ will be changed. This should definitely be mentioned there (and this is what I was looking for :)).

I was confused by the second article: why to preserve order, when it is preserved by default, as the 1st article reads? Now I think the second article should not be under heading _Imports order_ because it says something about all groups, not only imports!

The third thing: when I copy the first statement from the docs, Robotidy complains:
`Error: Configuring transformer 'OrderSettingsSections' failed. Verify if correct name was provided. Did you mean:                                                                                                                                 OrderSettingsSection`
There is an extra "s".... :( 

To conclude: Robotidy _can_ do what I wanted, but please take this issue as a request for changing documentation as I wrote above.

**Comment by bhirsz** [comment]
Good points - I will update the documentation. The documentation is always the hardest part (and most important) so if you see anything else that could be improved feel free to open the issue :)
