### ISSUE TITLE
Transformer: Normalize section header names

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-tidy#29]
Transformer for normalizing section headers names (ie from * test case * to *** Test Cases ***). 

Part of original tidy so it's related to #2

**Comment by mnojek** [comment]
I remember we were discussing this and we concluded that it will be good to give user a power to choose between uppercase settings and titlecase. So it would be good to support both `*** Settings ***` and `*** SETTINGS ***`.
The reason I think the second should also be available is that it's more visible when scrolling fast through file and you can quickly find where each section begins or ends.

**Comment by bhirsz** [comment]
Yes, I had this feeling at the bakc of my head about adding upper case possibility :D I will update PR with it

**Comment by bhirsz** [comment]
Updated + I also added option to select section (with --startline and --endline).
