### ISSUE TITLE
New transformer adding a space after `#` when missing

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-tidy#290]
Robocop, rule 0702, complains "Missing blank space after comment character" when it comes across `#some comment`. I like to have a transformer adding a space after `#` when missing;

**Comment by bhirsz** [comment]
``NormalizeComments`` transformer that handles it was just released in Robotidy 4.0! However I recommend waiting till the Robotidy 4.0.1 is (soon) released because I introduced regression.
