### ISSUE TITLE
Split 'spacecount' into two settings

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-tidy#293]
Now, `spacecount` settings sets number of space characters both for indentation and for separating (a keyword and its) arguments. However, almost all members of our team tend to indent with 4 spaces but on the other hand they separate arguments with 2 spaces. Like that:
```
FOR-IN-ENUMERATE
    FOR  ${index}  ${item}  IN ENUMERATE  @{LIST}
        My Keyword  ${index}  ${item}
    END
```
I think the reason of this is that a space character is less noticeable when surrounded with other spaces (like when used for indentation) than when it is surrounded with non-white characters (like when separating arguments). So in the first case one needs to use more spaces than in the other one to have similar perception of distance between things...

Shortly: please, could you split `spacecount` into two independent settings: one for indentation and the other one for separating things?

**Comment by bhirsz** [comment]
Sounds plausible and useful. 

I can add ``indentation`` (or ``indent``) and ``separatorcount`` (temporary name, I don't have good idea.. we have --separator already for type of the separator - space or tab). If there are not set it can use (old) ``spacecount`` setting value. 
Optionally we can only add ``indentation`` which by default would be equal to ``spacecount`` -> so it would be possible to:

indent 4 spaces separator 2 spaces
```
robotidy --indentation 4 --spacecount 2 .
```
indent 2 spaces separator 4 spaces
```
robotidy --indentation 2 --spacecount 4 .
```
indent 4 spaces separator 4 spaces
```
robotidy --spacecount 4 .
```

**Comment by bhirsz** [comment]
Linked PR. Most transformers try to be non-destructive to indents/separators if possible that's why most of the work was done in NormalizeSeparators transformer. Let me know after next release if I missed something.
