### ISSUE TITLE
Make rich_click an optional dependency

### ISSUE THREAD

**Issue by fabioz** [MarketSquare/robotframework-tidy#303]
rich_click has lots of dependencies and ideally I'd like to be able to use robotframework-tidy without those (my use case is vendoring robotframework-tidy in the language server, and it's kind of a small pain to get all those deps for the cli when all that's needed is using the internal api).

Maybe an option could be creating a `robotframework-tidy-core` with the minimum amount of dependencies and then having `robotframework-tidy` with the big dependencies for the cli...

**Comment by bhirsz** [comment]
It totally makes sense since it's only required for cli, not API. I can't use extras_require (since by default I want to have more dependencies and for some cases use less dependencies). I could either go with core package or figure out different method - I will think about it.

**Comment by bhirsz** [comment]
The other option is just make click-rich as optional dependency - [rich] profile for those all those who want to have rich outputs. It will be the easiest to pull off although it will require users to extend their install command. The pros would be no bloating especially for people running robotidy in CI.

**Comment by fabioz** [comment]
Seems good to me. Thanks for the fix.
