### ISSUE TITLE
Transformer: Rename test with uppercase words

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-tidy#305]
I made this
```
from robot.api.parsing import ModelTransformer, Token


class CamelCaseTestCaseTransformer(ModelTransformer):
    def visit_TestCaseName(self, node):  # noqa
        token = node.get_token(Token.TESTCASE_NAME)
        if token.value:
            token_value = ""
            for word in token.value.split(" "):
                token_value = f"{token_value} {word[0].upper()}{word[1:]}"
            token.value = token_value.strip()
        return node
```
for [Browser](https://github.com/MarketSquare/robotframework-browser/pull/2062/commits/78ebb69203ba5757686e6a46d7857a200c24aca5) library, but I was wondering would it be generally useful as a default converter?

**Comment by bhirsz** [comment]
Maybe it's possible to achieve it with RenameTestCases? For example add parameter capitalize_each_word=False and:

@staticmethod
def capitalize_each_word(match):
    return " " + m.group(1)[0].upper() + m.group(1)[1:],

if capitalize_each_word:
     token.value = re.sub("(\s+)(\w+)", self.capitalize_each_word, string=token.value))

**Comment by aaltat** [comment]
That is better idea, I will try to make PR at some point.
