### ISSUE TITLE
Wrong indentation on nested items

### ISSUE THREAD

**Issue by FiedlerJan** [MarketSquare/robotframework-tidy#317]
With robot framework version 5.0 TRY/EXCEPT was added and we started using it in our tests. We have a nested call of the TRY/EXCEPT in an IF/ELSE statement. If the robotidy is used the indent gets corrects wrongfully. I have tried multiple configurations without an correct result. Currently the only option is to disable robotidy for the whole IF/ELSE section.

Used robotidy version 2.5. 

Attached you will find an example of the conversion.

```
    # robotidy: off
    IF    '${host}' != 'X'
        ${command} =    Replace String    ${command}    host    127.0.0.1
    ELSE
        TRY
            ${ip} =    Get Container Ip Address
            ...    ${ip_x}
            ...    ${network_x}
        EXCEPT
            ${ip} =    Set Variable    123.4.5.6
        END
        ${command} =    Replace String    ${command}    host    ${ip}
    END
```

Result without 'robotidy: off'

```
    IF    '${host}' != 'X'
        ${command} =    Replace String    ${command}    host    127.0.0.1
    ELSE
        TRY
        ${ip} =    Get Container Ip Address
        ...    ${ip_x}
        ...    ${network_x}
        EXCEPT
        ${ip} =    Set Variable    123.4.5.6
    END
    ${command} =    Replace String    ${command}    host    ${ip}
    END
```

**Comment by bhirsz** [comment]
Do you have Robot Framework 5.0 installed in the environment you're using for robotidy? I've checked and it does indent correctly for me - but with 5.* installed. If I install RF 4 it will result in the output from your example.

**Comment by FiedlerJan** [comment]
You are right. Since I have multiple environments, I forgot to update everything. Thanks for pointing it out.
