### ISSUE TITLE
[Transformer] whitespace normalizer (except new lines)

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-tidy#32]
Normalize separators (whitespace between arguments etc) and indents. 

Related #2. 

Indent could be auto detectable for those who have custom indents ie:

```
Test
[Template]  I am test template
                ${first_arg}
                ${second_arg}
                ${misaligned_arg}
```
(that's also how robocop detect if line is under/over indented -> it checks lines around statement for comparison)

For first version we should use fixed value (4 spaces, configurable).

**Comment by MrMino** [comment]
Note: `SplitTooLongLines` from #14 does this too.

**Comment by MrMino** [comment]
Related w/ robotframework/robotframework#3891

**Comment by bhirsz** [comment]
Quite a lot of transformers does normalize the whitespace - but only within their scope of work (because we don't want to end up with misaligned code ;)). That's why we need separate transformer only for separators. 

Default separator length is 4 spaces, all tabs should be removed, indentation level honoured.
