### ISSUE TITLE
Support chars ÁáÉéĚěÍíÓóÚúÝýŮůŘřŤťŠšĎďŽžČčŇň in CLI mode

### ISSUE THREAD

**Issue by Reddriver** [MarketSquare/robotframework-tidy#324]
Is it possible to support czech diacritics?
![image](https://user-images.githubusercontent.com/7867213/173594586-01ea57ea-a7b4-42d8-954d-3204dcbc9eec.png)

**Comment by bhirsz** [comment]
Do you mean that when your'e using - - diff option it does skip chars with different encoding? As it's on the screen. Thanks for reporting it - it's definietly a bug.

**Comment by Reddriver** [comment]
Retest OK, thank you.
