### ISSUE TITLE
Keywords containing dot followed by space incorrectly renamed

### ISSUE THREAD

**Issue by Zeckie** [MarketSquare/robotframework-tidy#344]
When a keyword name contains `. ` (a dot followed by a space) or `._` and `RenameKeywords` is enabled, uppercase letters later in the keyword are incorrectly duplicated, overwriting other letters. The same also happens for keyword starting with an underscore.

Before:
```robotframework
*** Test Cases ***
Foo
    Foo. BAR Baz A b C
    _Foo bar BAZ

*** Keywords ***
Foo. BAR Baz A b C
    Log    Foo

_Foo bar BAZ
    Log    Foo
```

After:
```robotframework
*** Test Cases ***
Foo
    Foo.BBARBBz AAB C
    FFo Bar BBA


*** Keywords ***
Foo.BBARBBz AAB C
    Log    Foo

FFo Bar BBA
    Log    Foo
```

Config:
```yaml
[tool.robotidy]
configure = ["RenameKeywords:enabled=True"]
```

**Comment by bhirsz** [comment]
I can reproduce it, thanks for the report, I will take a look.
