### ISSUE TITLE
Add an unnecessary tab to inline if

### ISSUE THREAD

**Issue by levlist** [MarketSquare/robotframework-tidy#349]
Hi,

If I run robotidy on RF5 inline IF which is equivalent to the former "Return From Keyword If" it inserts an extra tab.
I haven't tried other scenarios. It was caught on robotidy 2.6.0.

![image](https://user-images.githubusercontent.com/10905822/177178908-50b8057c-611d-4ba9-8d03-27d466a01170.png)

I used the default settings and that file is prepared for the report, that's why I only added the diff as a screenshot.

**Comment by bhirsz** [comment]
Thanks for the report, I've added extra handling for inline if indentation recently but looks like I forgot to also check for RETURN statement (it does only works for keyword calls). I will fix it
