### ISSUE TITLE
Bug: keywords inside an IF-block are indented badly

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-tidy#356]
When `Run Keyword If` is replaced with IF-block, the keywords inside the block are indented with incorrect number of spaces. E.g.:
```
    ${a}  Run Keyword If  ${b} - ${e} <= ${c} and ${b} > 10  Evaluate  ${d} + 2 + (10 - ${c})  ELSE  Evaluate  ${d} + 2
```
is transformed to
```
    IF  ${b} - ${e} <= ${c} and ${b} > 10
      ${a}  Evaluate  ${d} + 2 + (10 - ${c})
    ELSE
      ${a}  Evaluate  ${d} + 2
    END
```
when using spacecount = 2 and indent = 4 (and line_length is too small for the whole expression to be on one line). Note there are only 2 spaces as the last indentation level of the lines beginning with `${a}`.

**Comment by bhirsz** [comment]
I've tried to reproduce it and I got:
```
*** Keywords ***
Keyword
 ${a}  IF  ${b} - ${e} <= ${c} and ${b} > 10
    Evaluate  ${d} + 2 + (10 - ${c})
  ELSE
    Evaluate  ${d} + 2
  END

```
So I can confirm there is bug with indentation, but also for some reason I got ${a} before ``IF`` - I need to investigate why it happened.
