### ISSUE TITLE
Toml configuration examples in docs underlines spaces

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-tidy#369]
![image](https://user-images.githubusercontent.com/8532066/181917224-ab9118b7-b269-4e69-9ce7-1c7c1f3266e8.png)

It's barely visible but could lead to confusion. We could either try to set code block parser to toml or change theme settings.

**Comment by bhirsz** [comment]
After some testing I think the best option would be.. migrating to another theme. It can be easily done in the one we're using (alabaster) but I've noticed that docs looks better in the other theme (furo). Several other minor issues will be also fixed in the furo theme. The additional benefit is that we're already using furo for robocop docs. The documentation will be more consistent across our tools (and it will be easier to maintain the docs).

**Comment by glueologist** [comment]
underscores are very visible if a browser plugin such as Dark Reader is used.

they confused me at first reading of docs and made comment in RF users group.  Finally discovered it was plugin that made them visible.
