### ISSUE TITLE
AlignTemplatedTestCases fails with Pipe separators

### ISSUE THREAD

**Issue by glueologist** [MarketSquare/robotframework-tidy#374]
Orig file with pipe separators:

```
*** Settings ***
| Test Template  | Test Add IPv4 Addresses
| Resource       | network_keywords.robot

*** Test Cases ***
| Typical | 4.4.4.4
| Loopback | 127.0.0.1
| Loopback subnet | 127.225.21.1
| Smallest | 1.1.1.1
| Largest  | 255.255.255.254
| Non-routable A-class | 10.10.1.1
| Class C prefix | 11.10.10.1 | 24
| Two Hosts prefix | 1.2.3.4 | 30
| Point to Point prefix | 4.3.2.1 | 31
```

Transform:

- leading pipe is not removed so this is invalid syntax - either all spaces or all pipe separators allowed per table
- test template data is not aligned

```
 robotidy  --transform AlignTemplatedTestCases --output transform_pipe.robot orig_src.robot

*** Settings ***
| Test Template  | Test Add IPv4 Addresses
| Resource       | network_keywords.robot

*** Test Cases ***
| Typical                          4.4.4.4
| Loopback                          127.0.0.1
| Loopback subnet                          127.225.21.1
| Smallest                          1.1.1.1
| Largest                          255.255.255.254
| Non-routable A-class                          10.10.1.1
| Class C prefix                          11.10.10.1          24
| Two Hosts prefix                          1.2.3.4             30
| Point to Point prefix                          4.3.2.1             31
```

**Comment by glueologist** [comment]
When doing a configure, so some other default transformers are run (I suspect), output is valid but not aligned

```
$ robotidy  --configure AlignTemplatedTestCases --output transform_pipe.robot orig_src.robot

*** Settings ***
Resource            network_keywords.robot

Test Template       Test Add IPv4 Addresses


*** Test Cases ***
Typical    4.4.4.4
Loopback    127.0.0.1
Loopback subnet    127.225.21.1
Smallest    1.1.1.1
Largest    255.255.255.254
Non-routable A-class    10.10.1.1
Class C prefix    11.10.10.1    24  
Two Hosts prefix    1.2.3.4    30  
Point to Point prefix    4.3.2.1    31  
```

**Comment by glueologist** [comment]
My rig versions:
```

        Tool |      Version      
-------------+-------------------
  Linux Dist | Ubuntu 20.04.4 LTS
Linux Kernel | 5.15.0-41-generic
      Python | 3.8.10
          RF | 5.0
 RF Selenium | 6.0.0
 RF Requests | 0.9.2
    Selenium | 4.1.5
    Requests | 2.27.1
```

**Comment by glueologist** [comment]
NormalizeSeparators is what allows AlignTemplatedTestCases to output valid .robot code.  This works, as expected, but requires two distinct steps.  A config file cannot be used to produce the same.

With same original file as above:
```
$ robotidy  --transform NormalizeSeparators --output transform_normal.robot orig_src.robot
$ cat transform_normal.robot

*** Settings ***
Test Template    Test Add IPv4 Addresses
Resource    network_keywords.robot

*** Test Cases ***
Typical    4.4.4.4
Loopback    127.0.0.1
Loopback subnet    127.225.21.1
Smallest    1.1.1.1
Largest    255.255.255.254
Non-routable A-class    10.10.1.1
Class C prefix    11.10.10.1    24  
Two Hosts prefix    1.2.3.4    30  
Point to Point prefix    4.3.2.1    31  

$ robotidy  --transform AlignTemplatedTestCases --output transform_align.robot transform_normal.robot

$ cat transform_align.robot

*** Settings ***
Test Template    Test Add IPv4 Addresses
Resource    network_keywords.robot

*** Test Cases ***
Typical                     4.4.4.4
Loopback                    127.0.0.1
Loopback subnet             127.225.21.1
Smallest                    1.1.1.1
Largest                     255.255.255.254
Non-routable A-class        10.10.1.1
Class C prefix              11.10.10.1          24
Two Hosts prefix            1.2.3.4             30
Point to Point prefix       4.3.2.1             31


```

**Comment by glueologist** [comment]
Using a single step with a configure file and the original src file above:

Config .toml file:
```
[tool.robotidy]
transform = [
    "NormalizeSeparators",
    "AlignTemplatedTestCases"
]
```
The output is not aligned.  While a two step will produce expect output a single step with list exclusive of transformers does not

```
$ robotidy  --config ./transform_config.toml  --output transform_align.robot orig_src.robot

$ cat transform_align.robot

*** Settings ***
Test Template    Test Add IPv4 Addresses
Resource    network_keywords.robot

*** Test Cases ***
Typical                            4.4.4.4
Loopback                            127.0.0.1
Loopback subnet                            127.225.21.1
Smallest                            1.1.1.1
Largest                            255.255.255.254
Non-routable A-class                            10.10.1.1
Class C prefix                            11.10.10.1          24
Two Hosts prefix                            1.2.3.4             30
Point to Point prefix                            4.3.2.1             31
```

**Comment by glueologist** [comment]
WORK AROUND:

```
robotidy  --transform  NormalizeSeparators <all src files>
robotidy  --config ./work_around.toml <all src files>
```

where the work_around.toml has the remaining transformers in a transform list with AlignTemplatedTestCases first.  

Since this works it would seem if the config.toml had the transfrom list with NormalizeSeparators first and AlignTemplatedTestCases second it should also work, but it does not.  The output from NormalizeSeparators has to be written out first.

Strange.

work_around.toml tested with so far:

```
[tool.robotidy]
spacecount = 4 
indent = 3 
continuation-indent = 2 # does not affect *** Settings **** tables; only in Keywords and Test cases
separator = "space"

transform = [ 
    "AlignTemplatedTestCases",
    "MergeAndOrderSections: order = settings,variables,testcases,keywords,comments",
    "AlignSettingsSection: up_to_column=2",
    "OrderSettingsSection: new_lines_between_groups = 0"
]
```

**Comment by bhirsz** [comment]
Transform option runs only selected transformers and since transformers are mostly independent, sometimes it could cause inproper behavior if you missing "important" transformer. In this case like you noticed aligner transformers does not work well with pipe syntax, that's why using NormalizeSeparators first is necessity.

Hovewer the need of writing the changes back to disk indicate there could be issue somewhere - I fixed something similar recently where one transformer modified attributes that did only update for other transformers after rereading from disk (I fixed that). I will take a look what it could be in this situation. Thanks for testing

**Comment by bhirsz** [comment]
Did you get any of my replies to robot Framework group threads? Not sure if it went through.

In one of my emails I pointed that you need to set --separator option for pipes to work. But I didn't create robotidy with pipes in mind and all our acceptance tests runs on spaces. That's why there could be some issues like yours. But your idea of replacibg all pipes to spaces then having another transformer that would at the end of run replace spaces with pipes would be most robust / stable solution. I would be able to cover that one transformer with proper tests.

**Comment by bhirsz** [comment]
I've checked and I see that ``--separator`` only takes spaces and tabs - my mistake. So in the end we still would need new transformer for handling conversion back to pipes (if someone needs it).

**Comment by glueologist** [comment]
I do not see any replies from you in the users group.  I did see you opened a couple of bugs from my other comments after I found robotidy github repo.  Which is great.  I went looking to see what other bugs I might run into. :-)

It would be great if you could add pipe separator support.  

I also agree with overall methodology when dealing with anything other than a space separator:  first normalize to space separator, run all desired transforms, than normalize back to what ever separator desired.  

This just needs to be very clear in the docs, which I am sure you see from the extensive work you have already done on the docs!

Also needed in docs is the order transforms are run by default and any gotchas if a different order is used. (there is one warning about order now, but I cannot remember where right now.)

Thanks for the tool.  I used robot.tidy only for doc generation.  Mainly to remove pipes for better readability.  But with robotidy, once it supports pipes, I could see it used as a code beautifier on a pre-commit hook.

**Comment by bhirsz** [comment]
Fixed the issue in linked PR - it was suprisingly easy to fix - just need to handle small pecularity coming from pipe separator syntax. Also improve docs a bit. Support for pipes is already tracked by other issues as well.
