### ISSUE TITLE
Add support for argument_indent for Settings tables in resouce files

### ISSUE THREAD

**Issue by glueologist** [MarketSquare/robotframework-tidy#380]
Currently, from docs and my testing, the argument_indent argument for the AlignSettingsSection transformer only works on Suite Setup, Suite Teardown, Test Setup and Test Teardown.  It does not work  in a Settings table in a resource file.

This bug is a request to enhance support to cover this.

Example of what transformer does now in a resource file, even with the argument_indent given:
```
*** Settings ***
Documentation
...            Provides access to all Keywords needed for interaction with Toucan GUI.
...            For more details on what must be set to use this library, see documentation 
...
Library        String
Library        Collections
Library        RequestsLibrary
Library        OperatingSystem
Library        SensorSwitchRig
...            gmswRig    001
Library        SeleniumLibrary
...            timeout=${TIMEOUT}
...            implicit_wait=${TIMEOUT}
...            run_on_failure=Capture Page Screenshot
...            screenshot_root_directory=${OUTPUT DIR}
Resource       vertiv_parameter_unicode.robot
Resource       vertiv_lol_sensor_rig.robot
Variables      geist_toucan_constants.py
```

Example of what would be nice:
```
*** Settings ***
Documentation
...            Provides access to all Keywords needed for interaction with Toucan GUI.
...            For more details on what must be set to use this library, see documentation 
...
Library        String
Library        Collections
Library        RequestsLibrary
Library        OperatingSystem
...                gmswRig    001
Library        SeleniumLibrary
...                timeout=${TIMEOUT}
...                implicit_wait=${TIMEOUT}
...                run_on_failure=Capture Page Screenshot
...                screenshot_root_directory=${OUTPUT DIR}
Resource       vertiv_parameter_unicode.robot
Resource       vertiv_lol_sensor_rig.robot
Variables      geist_toucan_constants.py
```

**Comment by bhirsz** [comment]
Sounds good. Essentially we need to add this to ``Library`` setting? (I need to check what other settings also support arguments, I think that also ``Variables`` for py files accept arguments). Your second example looks more readable - a good example for the "Robot Framework style guide workshop". Small note that in this case it does not split it to multiline, it only indent if the setting is already multiline. I will update ``SplitTooLongLine`` to also cover too long settings in the future, so it's good time to improve this formatting.

And I need to decide what to do with ``WITH NAME`` / ``AS``.

Orig:
```
Library    SeleniumLibrary
...        timeout=${TIMEOUT}
...        WITH NAME
...        Selenium
```

Indent like all other arguments:
```
Library    SeleniumLibrary
...            timeout=${TIMEOUT}
...            WITH NAME
...            Selenium
```
don't intend ``WITH NAME`` /  ``AS``, case when all is multiline:
```
Library    SeleniumLibrary
...            timeout=${TIMEOUT}
...        WITH NAME
...            Selenium
```
don't intend ``WITH NAME`` /  ``AS``, case name is next to ``WITH NAME`` / ``AS``:
```
Library    SeleniumLibrary
...            timeout=${TIMEOUT}
...        WITH NAME    Selenium
```

**Comment by glueologist** [comment]
I vote for the last one where WITH NAME is not indented and the new name is on the same line, but the one with the new name also indented is a very close 2nd.  Both read well.

I have no insight on calling args on Resource or Variables files but if so then indent the same would read the best.

Thanks for being open to all the changes I have been discussing lately.  I understand openness is not the same as committing to the changes, but it is nice to suggest improvements and they be seriously considered.

I am excited about having a good code beautifier for RF.  Thx for your effort!

**Comment by bhirsz** [comment]
And I'm glad for having the feedback and test. Unfortunately I'm currently not in the company that uses Robot Framework so I'm not the user myself. It makes harder to catch bugs or notice missing features. But that's the reason Robotidy is heavily community driven - I implement most of the code but I'm getting feedback from the users which I'm glad for :) For example one of the recent transformers (aligners) was created because I have noticed it popular request during robocon 2022 and then I was contacted by one of the users that helped me achieved current state after lots of feedback rounds (aligners are tough subject so it is still area where we can improve though, especially templated tests).

**Comment by bhirsz** [comment]
Linked PR - ``WITH NAME`` is ignored and not indented. And since only first separator in every line in multiline settings is intended, the user can decide either he want to keep aliased name of the library together with ``WITH NAME`` or in separate line.

For example this (invalid but for sake of reference):
```
Library    LibraryName
...    arg    arg2
...    WITH NAME    alias1
...    arg3
...    WITH NAME 
...    alias2
```
would be transformer to:
```
Library    LibraryName
...        arg    arg2
...    WITH NAME    alias1
...        arg3
...    WITH NAME 
...        alias2
```
