### ISSUE TITLE
OrderSettings custom order doc missing details

### ISSUE THREAD

**Issue by glueologist** [MarketSquare/robotframework-tidy#381]
Not sure if this is a doc issue or a logic bug.

If custom order is requested both keyword_before and keyword_after must be specified.  Even if nothing is given for keyword_after.  If  the empty keyword_after= is not given the [Teardown] setting gets written twice.

It could be a doc issue only.  The doc does refer to using the empty keyword_after= syntax, but does not state it is required.

I have not yet tested the test_before and test_after param.  Will update if similar behavior is seen.

Examples:

Orig file, only the *** Keywords *** table is of interest in this context:
```
*** Settings ***
Documentation
...    Some docs on multiple lines
...    even more

Force Tags    Positive Test Cases    Full Regress
Resource    my_system_keywords.robot
Suite Teardown    A suite Teardown kw
Test Teardown    A Test Teardown kw
Suite Setup    A suite setup kw
Test Setup    A Test setup kw


*** Test Cases ***
Test All Settings
    [Documentation]    single line of docs
    [Tags]    Raven Only
    [Setup]    Switch DUT Access To HTTPS
    [Teardown]    Switch DUT Access To Default
    ${v}=    Geist Get    /api/sys/state/uptime
    Log To Console    \n${LOGIN URL}/api/sys/state/uptime = ${v}


*** Keywords ***
KW All Settings
    [Documentation]    single line of docs
    [Tags]    Raven Only
    [Arguments]    ${a value}
    [Teardown]    Switch DUT Access To Default
    ${v}=    Geist Get    /api/sys/state/uptime
    Log To Console    \n${LOGIN URL}/api/sys/state/uptime = ${v}
```

Toml config file with ONLY keyword_before param given:

```
[tool.robotidy]
separator = "space"   
spacecount = 4
indent = 3
continuation-indent = 2

transform = [
    "OrderSettings:keyword_before=documentation, tags, timeout, arguments, teardown"
]   
```
Produces this incorrect output for the KW with the [Teardown] setting listed twice: the requested locatiion and at the default at the end of KW.  Further testing shows no matter what order the original [Teardown] setting the output is the same as below:
```
*** Keywords ***
KW All Settings
    [Documentation]    single line of docs
    [Tags]    Raven Only
    [Arguments]    ${a value}
    [Teardown]    Switch DUT Access To Default
    ${v}=    Geist Get    /api/sys/state/uptime
    Log To Console    \n${LOGIN URL}/api/sys/state/uptime = ${v}
    [Teardown]    Switch DUT Access To Default
```

'Fixed' Toml config file with empty keyword_after= param

```
[tool.robotidy]
separator = "space"   
spacecount = 4
indent = 3
continuation-indent = 2

transform = [
    "OrderSettings:keyword_before=documentation, tags, timeout, arguments, teardown:keyword_after="
]   
```

Produces expected output for KW:
```
*** Keywords ***
KW All Settings
    [Documentation]    single line of docs
    [Tags]    Raven Only
    [Arguments]    ${a value}
    [Teardown]    Switch DUT Access To Default
    ${v}=    Geist Get    /api/sys/state/uptime
    Log To Console    \n${LOGIN URL}/api/sys/state/uptime = ${v}
```

**Comment by bhirsz** [comment]
If you don't overwrite setting it will be default, that's how you got teardown in two places. I consider it as a bug, settings should not duplicate between before/after "sections".

**Comment by glueologist** [comment]
At least it has a work around.

**Comment by glueologist** [comment]
An additional issue in this context that again might be a doc issue only.  (or I am confused. ;-) )

The doc page on configuration file states and give example:

**_Transformers with multiple parameters can be configured in one line (each param delimited by :) or in separate lines_**

But below seems to silently fail in that the custom order for Test Case settings is not transformed.  Instead the default order is transformed.  The keyword settings are transformed to the custom order requested.

(Do I have a syntax error in the toml file?  robotidy has been spot on with a good error msg when I have done that)

```
[tool.robotidy]
separator = "space"
spacecount = 4 
indent = 3 
continuation-indent = 2 

transform = [ 
    "OrderSettings:test_before=tags, setup,  teardown, documentation:test_after=",
    "OrderSettings:keyword_before=tags, teardown, documentation, arguments:keyword_after="
]

```
This toml config file gives what I expect with both TC and KW settings in custom order:

```
[tool.robotidy]
separator = "space"
spacecount = 4 
indent = 3 
continuation-indent = 2 

transform = [
    "OrderSettings:test_before=tags, setup,  teardown, documentation:test_after=:keyword_before=tags, teardown, documentation, arguments:keyword_after="
]

```

**Comment by bhirsz** [comment]
For the initial issue in this thread: I will add logic that will remove duplicate setting names if only one of the settings is configured.

There is also situation if you configure two parameters (after/before order) and leave out one of the settings. By documentation it should remove this setting from the code. It could be desired behavior in most cases it's probably invalid config from the user. I will add a warning message (something along "X setting is omitted from both Y/Z. It will be removed from the code. If it's not intented behaviour, add it to either Y or Z).

**Comment by bhirsz** [comment]
Multiline configuration works only for --configure. If you do:
```
transform = [ 
    "OrderSettings:test_before=tags, setup,  teardown, documentation:test_after=",
    "OrderSettings:keyword_before=tags, teardown, documentation, arguments:keyword_after="
]
```
it will schedule OrderSettings to run with the latest configuration (``"OrderSettings:keyword_before=tags, teardown, documentation, arguments:keyword_after="``). 

To use only one transformer and use multiline configuration you would need to:
```
[tool.robotidy]
separator = "space"
spacecount = 4 
indent = 3 
continuation-indent = 2 

transform = [
    "OrderSettings"
]
configure = [ 
    "OrderSettings:test_before=tags, setup,  teardown, documentation:test_after=",
    "OrderSettings:keyword_before=tags, teardown, documentation, arguments:keyword_after="
]
```

I believe it could be improved in our docs (I will open a separate issue for it later). Note that ``--transform`` while is used for selective runs and could accept configuration, it does not support all options like ``--configure``. And mention in the multiline configuration option that it only works for ``--configure``, maybe even provide this example how to do this with ``--transform``.

**Comment by bhirsz** [comment]
And (optionally) if user specify multiple ``--transform`` with the same name, provide user warning that only the latest one is used.

**Comment by bhirsz** [comment]
Decided on bit different approach in the linked PR. If the user omits the setting name from both before/after orders it will be ignored (user will notice it by running the formatting anyway). If the user provides duplicate name in any of the order or order pair (like test_after and test_before) it will raise an exception.

In previous post I mentioned I wanted to automatically remove the setting if is present in the order but I've decided not to - it's best no to fix configuration provided by the user, but fail if the configuration is invalid.
