### ISSUE TITLE
Transfomers should be configurable

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-tidy#4]
Code transformers should be configurable. For example if we're adjusting number of lines between test cases, we should be able to override default value. 

With multiple possible transfomers (and option to add external ones) it's important to have uniform way of configuring them. I would propose something along:

```
robotidy --configure <name_of_transformer>:<name_of_configurable>:<value>
```

To ease development we could add `@configurable` wrapper that will automatically list function as variable setter(it will be helpful to list all configurable values for transformer if we provide name with typo/not existing configurable):

```
class DummyTransfomer(ModelTransfomer):
    @configurable
    def test_case_spacing(value):
       self._test_case_spacing = int(value)
```

**Comment by pekkaklarck** [comment]
How to do this depends on how transformers themselves are enabled or disabled. An alternative system would be each transformer getting a separate cli option that would then allow configuration:

**Comment by bhirsz** [comment]
So you're proposing to replace --mode with --transform? I actually like this idea but I agree that providing multiple parameters isn't handy even with =. I've created #5 to countermeasure it.

**Comment by bhirsz** [comment]
I will use mentioned in first post logic and something similiar to RF @library and @keyword decorators. It will allow to easily select what class from file is transformer and what method is configurable setter:

```
@transformer
class DummyTransfomer(ModelTransfomer):
    @configurable
    def test_case_spacing(value):
       self._test_case_spacing = int(value)
```

We can also use @transformer decorator to change behaviour of the transformer, ie accept or ignore some of the global options. I dont have any specific feature in mind but it will be easily extendable.
