### ISSUE TITLE
RenameKeywords transformator changes object name

### ISSUE THREAD

**Issue by Semperdecus** [MarketSquare/robotframework-tidy#417]
**given:**
Testcase:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/26483574/193599146-d4405dfb-a3cc-4fb9-81fc-44e7c4a3cd3f.png">

With configurations:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/26483574/193598821-832d14fe-9c42-46ce-be33-c00edab4b2f1.png">

**Expected:** 
nothing changes

**Actual:** 
the last character after the dot becomes a capital letter which causes the test to fail since `user.Password` is undefined.
<img width="597" alt="image" src="https://user-images.githubusercontent.com/26483574/193599244-026318cc-c02d-4a65-9797-bb0f875a3e6d.png">

This has to do with the [RenameKeywords transformer's ignore_library parameter](https://robotidy.readthedocs.io/en/latest/transformers/RenameKeywords.html). We'd like a way to turn this parameter off completely so nothing changes.

Thanks in advance

**Comment by bhirsz** [comment]
Thanks for the issue, it should ignore the variables. I will check the logic for renaming the keywords.

**Comment by bhirsz** [comment]
I fixed it - I will raise PR and release it today together with other fixes. I used some of the internal Robot Framework logic for dealign with variables in names and it works much better (ie. we also manage to handle ${user['dictionaries']}).

**Comment by Semperdecus** [comment]
Just validated that this works. Thanks for solving this so quickly!
