### ISSUE TITLE
`rich` should be an optional dependency

### ISSUE THREAD

**Issue by fabioz** [MarketSquare/robotframework-tidy#419]
This was true in an older version, but now the import:

`from robotidy.api import transform_model` 

fails if `rich` is not installed (on robotidy 3.2).

**Comment by bhirsz** [comment]
Fixed in linked PR. I have decided to refactor our imports bit more (it's a mess, now bit less but still not ideal). I also added some extra code to decrease the chance of it happening in the future. Let's hope it will not repeat in the next release ;)
