### ISSUE TITLE
[Bug] Wrong indentation for BREAK in inline IF

### ISSUE THREAD

**Issue by ferroiz** [MarketSquare/robotframework-tidy#422]
Hi,
Almost exactly as in #349 I'm having issues with the BREAK (instead of RETURN) indentation inside inline IF:
![image](https://user-images.githubusercontent.com/82469806/195116952-2bc71a8c-49fb-4317-a632-1e5a69b434fb.png)

I guess the BREAK statement also has to be added in the indentation handling for those inline cases, right?

**Comment by bhirsz** [comment]
Ups! Same goes for CONTINUE - at this point I need to take a look if there is a better option to handle such cases so avoid silly mistakes like this. Thanks for reporting
