### ISSUE TITLE
Support all python versions RF 4.0 supports

### ISSUE THREAD

**Issue by admorgan** [MarketSquare/robotframework-tidy#43]
I have a number of Ubuntu 18.04 systems that do not support adding ppas, that use RobotFramework 4.0. It would help me if tidy supported all the versions of python the minimum supported version of RF supported (in this case 3.5).

**Comment by MrMino** [comment]
Given that almost all 3.5 code works under 3.7, what's stopping you from running _just_ robotframework-tidy on 3.7? You don't have to run the fromatter in the same environment you run the code that is being reformatted.

**Comment by admorgan** [comment]
I want to use the formatter on CI systems that don't have 3.7.

**Comment by MrMino** [comment]
You don't have to add ppas for it. Have you tried using [pyenv](https://github.com/pyenv/pyenv)? You should not rely on the interpreter version shipped with your distribution, it's almost always grossly outdated. Python 3.5 has been released almost 6 years ago.

**Comment by admorgan** [comment]
I know, it makes me sad every day I have to deal with this.

**Comment by admorgan** [comment]
Bigger question are you agreeable to accept patches to include older versions of python?

**Comment by bhirsz** [comment]
I would prefer to avoid to provide backward compability. I often see projects that try to support all Python versions (even 2) and the code can't use all new features (even with futures) and it overly complicates things. Python 3.5 lifecycle ends in this year (2021) and it's a lot less popular than next version (Python 3.6). 

But biggest problem is that we're allowing external transformers (you can develop your own and run it with tidy). 

What's limiting you from upgrading Python version in your ubuntu images? Lifecycle ends and not being able to use all packages are good arguments with discussion in management (been here, done that.. ).

**Comment by admorgan** [comment]
I happen to completely agree with you. Discussions with management have already been going on for some time, I just like to attack a problem from multiple fronts. Now I can focus on the other front.
