### ISSUE TITLE
Robotidy will replace Test Tags to Force Tags in settings section after RF6

### ISSUE THREAD

**Issue by siongwai** [MarketSquare/robotframework-tidy#432]
Environment:
- robotframework-tidy 3.3.1
- VS Code
- RF Language Server 1.3.5
- Robot framework 6.0
- Enable format on save in VS Code

Problem:
Scenario 1: 
Write Test Tags in the settings section of robot file. Then save the file.

Scenario 2:
Prepare a robot file which having Test Tags in the settings section, then run command "robotidy ." to tidy-up robot file

Outcome:
All the Test Tags will be replaced to Force Tags.

**Comment by bhirsz** [comment]
We're normalizing the setting names using the type names and unfortunately Force and Test Tags use the same type (Force Tags). I will add extra logic to handle it better in RF 6+. Thanks!

**Comment by bhirsz** [comment]
It looks like "NormalizeTags" is doing it - since we're recreating whole tag node instead of modyfing it.
