### ISSUE TITLE
Do not split variable if its not a list

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-tidy#436]
SplitTooLongLine transformer splits too long variables. It sometimes give us some benefits, ie:
```
${SHORT_NAME}
...    realy long value realy long value realy long value realy long value realy long value realy long value
```

But it's almost always run together with ``AlignVariablesSection`` defeating this benefit:

```
${SHORT_NAME}
...                                            realy long value realy long value realy long value realy long value realy long value realy long value
```

There should be configuration for SplitTooLongLine to only split variables if has more than 1 element (it can be later decided if should be default behaviour).

**Comment by Ga22be** [comment]
This is the issue I had which caused me to suggest #475
