### ISSUE TITLE
Run Keyword If changed to If causes test failures

### ISSUE THREAD

**Issue by aw-n-able** [MarketSquare/robotframework-tidy#450]
Discovered with version 3.3.1.
Enabling 'Format on Save' in Visual Studio Code can produce an unintended side effect, which is that not only the formatting is changed but the keyword too, as below. Note that the `Run Keyword If` command has been changed to `If`, which was causing failures in test runs.

Unformatted (correct):

```
SSH Delete Folders If Exists
	[Arguments]     ${LOCAL_ADMINISTRATOR_PASSWORD}     ${PATH}

	${out}	${err}	${rc}=	Execute Command		cd ${PATH}/agent		return_stdout=True  return_stderr=True  return_rc=True
	Run Keyword If			${rc}==${0}			SSH Delete Folder		${LOCAL_ADMINISTRATOR_PASSWORD}		${PATH}/agent

	${out}	${err}	${rc}=	Execute Command		cd ${PATH}/MMS			return_stdout=True  return_stderr=True  return_rc=True
	Run Keyword If			${rc}==${0}			SSH Delete Folder		${LOCAL_ADMINISTRATOR_PASSWORD}		${PATH}/MMS
```

Formatted:

```
SSH Delete Folders If Exists

    [Arguments]    ${LOCAL_ADMINISTRATOR_PASSWORD}    ${PATH}

    ${out}    ${err}    ${rc}=    Execute Command
    ...    cd ${PATH}/agent
    ...    return_stdout=True
    ...    return_stderr=True
    ...    return_rc=True
    IF    ${rc}==${0}
        SSH Delete Folder    ${LOCAL_ADMINISTRATOR_PASSWORD}    ${PATH}/agent
    END

    ${out}    ${err}    ${rc}=    Execute Command
    ...    cd ${PATH}/MMS
    ...    return_stdout=True
    ...    return_stderr=True
    ...    return_rc=True
    IF    ${rc}==${0}
        SSH Delete Folder    ${LOCAL_ADMINISTRATOR_PASSWORD}    ${PATH}/MMS
    END 
```

**Comment by bhirsz** [comment]
Hi, what kind of error did you get? Replacing ``Run Keyword If`` to ``If`` is done by ``Replace Keyword If`` transformer and it can be disabled. But IF syntax should work if you're using Robot Framework 4+.

And the reason why it is being replacing is that ``Run Keyword If`` is getting deprecated in favour for ``IF``. There are other cases like this in robotidy, for example ``[Return]`` is replaced with``RETURN`` in Robot Framework 5.0.+

**Comment by aw-n-able** [comment]
Hi @bhirsz unfortunately we no longer have log files covering the test failures for the `If `keyword replacement, so I can't investigate the difference in behaviour. We weren't aware that this was an intended feature so obviously this led to the problem. Thanks for your explanation.
