### ISSUE TITLE
Robotidy replaces 'Test Tags' by 'Force Tags' in settings section when 'OrderTags' transformer is used

### ISSUE THREAD

**Issue by mptok** [MarketSquare/robotframework-tidy#469]
# OrderTags Transformer Issue

## Env

- robotframework-tidy 3.3.3
- Robot framework 6.0.2
- PyCharm

## Steps

1. Use 'Test Tags' in the settings section of a robot file: 'Test Tags  Example-One  Example-Two'.  Then save the file.
2. Run robotidy with OrderTags  enabled

### Expected behavior

No changes should be made to that line.

### Observed behavior

'Test Tags' are replaced by 'Force Tags'. The line from the above will look like this: 'Force Tags  Example-One  Example-Two'

## Details

This is the same issue as it was reported [here](https://github.com/MarketSquare/robotframework-tidy/issues/432). There is yet another transformer to be fixed, namely 'OrderTags'. Maybe there is more of them. Please check that on your end.

**Comment by bhirsz** [comment]
Thanks for the report. It looks like I need to add ``Test  Tags`` to most acceptance tests to catch such situation. Probably only ``OrderTags`` is left but just to be sure.

**Comment by bhirsz** [comment]
Issue is solved in our develop branch. It will be included in the next release - I will reply in this thread after the release.

**Comment by bhirsz** [comment]
Change is now live in Robotidy 3.5.0.

**Comment by mptok** [comment]
Thank you!
