### ISSUE TITLE
API to format contents in-memory

### ISSUE THREAD

**Issue by fabioz** [MarketSquare/robotframework-tidy#49]
It'd be nice to have some API to format the contents in memory -- like was done in https://github.com/MarketSquare/robotframework-robocop/issues/168.

**Comment by bhirsz** [comment]
@fabioz How the transformer model should be returned? I could add method for transforming the model itself and then return it from method:
```
    def transform_model(self, model):
        for transformer in self.transformers:
            # do stuff
         return model
```
I could also add special flag True/False to determine if the model was modified (so we don't write back to file if not needed).

**Comment by fabioz** [comment]
Well, the final API is mostly applying code-formatting based on the user-configuration, so, I was thinking about something such as:

```
def transform_model(ast_model, config):
    '''
    :param ast_model: 
        The model to be transformed.
    :param config:
        The config with rules to be applied (usually created from Config(root_directory), where a 
        `robotidy.toml` or `pyproject.toml` file is searched based on root_directory or one of its parents).
    :return:
        The transformed model or None if no transformation took place.
    '''

def convert_model_to_str(ast_model):
    '''
    :return:
        The model converted to a string.
    '''
```

Then, the usual usage would be something as:

```
model = robot.get_model(filename)
new_model = transform_model(model, Config(root_dir))
if new_model is not None:
    s = convert_model_to_str(model)
    with open(filename, 'w') as stream:
        stream.write(s)
```

**Comment by bhirsz** [comment]
Ok thanks for example. Robotidy have different architecture than Robocop (the biggest difference is that Robotidy uses click and Robocop argparse with Config class). But I will try to have Robotidy API as close as possible to Robocop one - like in your example.

**Comment by bhirsz** [comment]
@fabioz 

I've created API - but it's bit of mix what you wanted. Tell me what you think. 

I've decided to create Robotidy instance and load config every time we call ``transform_model`` method (imported from robotidy.api). It have bit worse performance than creating instance once and calling transform_model on it (like we're doing in robocop API) but it's easier to use. transform_model also return model converted to str (or None) directly so we don't need to use ``convert_model_to_str``. 

Basic usage:
```
model = robot.get_model(filename)
transformed_model = transform_model(model, 'my_root_dir')
if transformed_model is not None:
    with open(filename, 'w') as stream:
        stream.write(transformed_model )
```

``transform_model`` automically finds and loads any configuration from robotidy.toml or pyproject.toml file. You can also pass few formatting parameters that will act as default values (but can be overwritten by config from toml files):

```
transformed_model = transform_model(model, 'my_root_dir', spacecount=8) # default for spacecount is 4
```

If it's ok I will merge this PR and create release 1.2.0 of Robotidy today.

**Comment by bhirsz** [comment]
Robotidy can transform selectively (meaning you can pick just one or two transformers) - it should be easy to allow to pass transformer names from the API too and ignore those from the *.toml files. 

It could be useful if you want to have separate methods for doing specific things, for example "Order imports" or "Align selected code". Please let me know if there will be need for it in the future. I will plan it

**Comment by fabioz** [comment]
Seems good to me ;)
