### ISSUE TITLE
Config file support

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-tidy#5]
robotidy should support configuration files. There are two ways of doing it:

* point to external file from cli:
```
robotidy --config config.txt
```
* automatically load configuration if found in directory with transformed file (`.robotidy` could be default name)

We should decide on either of two or both.

**Comment by mnojek** [comment]
I would suggest supporting both ways of loading file but will start with default path and fixed config name and then extend it to loading any file with the given name.

**Comment by pekkaklarck** [comment]
I think automatic loading of the config file is a must. Then a project can specify their rules in a config file and just using `robotidy tests.robot` is enough. Support for a separate option to load additional or alternative config file would be nice as well, though.

How are other similar tools handling this? Are there standard or third-party modules making this easy?

**Comment by bhirsz** [comment]
Most popular are `ini` and `toml` file types. Sometimes tools use also `yaml`. All of them have some third-party modules that supports parsing. It's hard to pick the best but both `yaml` and `toml` does support nesting the data (and it will be usefull for us). From both of them `yaml` require less boilerplate code to define our config. For example:

```
main:
    some_global_flag: True
    ignore_paths: 
        - *.resource
        - do_not_touch.robot
transformers:
    MyAwesomeCodeTransfomer:
        test_case_spacing: 4
```

The same in toml would be:
```
[main]
some_global_flag = True
  ignore_paths = ["*.resource", "do_not_touch.robot"]
[transformers]
    [transformers.MyAwesomeCodeTransfomer]
        test_case_spacing = 4
```

Retrieving the data is similiar there is either toml or pyaml module that loads the data in dict like format (config['transformers] etc)

**Comment by bhirsz** [comment]
Here is longer overview of possible configuration types: 
https://hackersandslackers.com/simplify-your-python-projects-configuration/

The conclusion is more or less 'use whatever you want, there isn't THAT big difference to overthink it'. That's why I vote for `yaml`.

**Comment by mnojek** [comment]
`toml` is used in many linters and I think it's more common across similar tools. `yaml` has a strange structure that can be not intuitive at first. I will opt for `toml` but since it's not a big difference I support each decision.

**Comment by bhirsz** [comment]
Decided on toml. Additional benefit is that toml support is builtin into Python and it was really easy to get it working.
