### ISSUE TITLE
transform NormalizeNewLines add option to disable "appends 1 empty line at the end of file"

### ISSUE THREAD

**Issue by IlfirinPL** [MarketSquare/robotframework-tidy#51]
Currently when editing using RIDE it will remove last line from file and it looks like change in file in git repository. 
When you tidy whole project this will be more changes to review.

**Comment by MrMino** [comment]
Possibly related: #47 

I think this stems from a misunderstanding of what's the difference between Unix-style EOL and DOS-style newline. As I understand it, with the former format, all text files should end with a newline character. With the latter it's not the case - all _lines_ should _start_ with a newline. IDEs tend to display this differently depending on the operating system on which they run.

For git, this is something that it can convert on the fly based on config options: see https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings

With regards to RF code, having `\n\n` at the end of the file is not something you should allow. It's akin to W391 in flake8 / pycodestyle:

> W391: blank line at end of file

IMO the normalizer should always ensure there's one and only one `\n` at the end of the file. If there's less - it could unnecessarily bork catenation between files. Not every utility is written with the "lack of last newline" issue in mind.

So if you see something like this in your diff:

![image](https://user-images.githubusercontent.com/6691643/112492827-e5c32080-8d81-11eb-9f8b-3071110ab623.png)

Then, unless the repository is meant to contain files solely for usage under Windows, this _is_ the Unixy-semanticly-correct behavior.

**Comment by IlfirinPL** [comment]
After executing tidy, development is always on windows machines so end of line is always same type end of line.
In all files there is extra line added compare code develop via RIDE
![image](https://user-images.githubusercontent.com/1460956/112495765-7ac71900-8d84-11eb-9a17-4e858ab9dabd.png)
![image](https://user-images.githubusercontent.com/1460956/112495405-2885f800-8d84-11eb-9f02-0ff7f4ed3b42.png)
![image](https://user-images.githubusercontent.com/1460956/112495640-5e2ae100-8d84-11eb-8086-cca511ae4ca0.png)

**Comment by bhirsz** [comment]
> After executing tidy, development is always on windows machines so end of line is always same type end of line.
> In all files there is extra line added compare code develop via RIDE
> ![image](https://user-images.githubusercontent.com/1460956/112495765-7ac71900-8d84-11eb-9a17-4e858ab9dabd.png)
> ![image](https://user-images.githubusercontent.com/1460956/112495405-2885f800-8d84-11eb-9f02-0ff7f4ed3b42.png)
> ![image](https://user-images.githubusercontent.com/1460956/112495640-5e2ae100-8d84-11eb-8086-cca511ae4ca0.png)

Its bug described in #47, already fixed and master and it will be soon released

**Comment by IlfirinPL** [comment]
Great then I will close this one

**Comment by MrMino** [comment]
Whoops, I thought that this is about the "no newline at the end of file" → "proper newline at the end of file" issue.

**Comment by IlfirinPL** [comment]
I tested with latest build from sources master branch and problem still persists

**Comment by MrMino** [comment]
@IlfirinPL  could you please give an example of a sourcefile and command to reproduce this with?

**Comment by IlfirinPL** [comment]
@MrMino  
command in powershell executed 
`robotidy --transform ReplaceRunKeywordIf --transform NormalizeSectionHeaderName --transform NormalizeNewLines --transform ReplaceRunKeywordIf  --transform DiscardEmptySections:allow_only_comments=True --transform SplitTooLongLine:line_length=250  --transform NormalizeSettingName  .
`
source file org 
[base.zip](https://github.com/MarketSquare/robotframework-tidy/files/6219775/base.zip)

file after change
[base-after.zip](https://github.com/MarketSquare/robotframework-tidy/files/6219783/base-after.zip)

**Comment by bhirsz** [comment]
> @MrMino
> command in powershell executed
> `robotidy --transform ReplaceRunKeywordIf --transform NormalizeSectionHeaderName --transform NormalizeNewLines --transform ReplaceRunKeywordIf --transform DiscardEmptySections:allow_only_comments=True --transform SplitTooLongLine:line_length=250 --transform NormalizeSettingName . `
> source file org
> [base.zip](https://github.com/MarketSquare/robotframework-tidy/files/6219775/base.zip)
> 
> file after change
> [base-after.zip](https://github.com/MarketSquare/robotframework-tidy/files/6219783/base-after.zip)

Thanks for the submitting issue, I will try to investigate it and fix it. Previous fix for this transformer was released yestarday in 1.1.1 (you can try too see if it helps, but it's the same code in master so I doubt it). I apologise for the late reply - I was busy with Robocop but now I should be free to work with Robotidy more.

**Comment by IlfirinPL** [comment]
@bhirsz  Greate News,  I have tested version 1.1.1, and problem did not appear its fixed
