### ISSUE TITLE
[Question] about dependency rich-click

### ISSUE THREAD

**Issue by d-biehl** [MarketSquare/robotframework-tidy#510]
Hi,

is there a reason that the dependency `rich-click` is pinned to version 1.4? Because of this, I cannot use higher version of rich-click in my projects. The actual version of rich-click is 1.6.1.

When I update the rich-click version with pip, pip says

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
robotframework-tidy 4.0.1 requires rich-click==1.4, but you have rich-click 1.6.1 which is incompatible.
```

maybe you can change the dependency to >=1.4?

**Comment by bhirsz** [comment]
No reason, I went with whatever was stable when I was adding rich click to tidy. I can bump version - but I will most likely keep closed requirement (up to 1.4.1 or whatever is most recent now) just to be safe. It is under active development and there were versions with regression.

**Comment by bhirsz** [comment]
And I will set dependabot to remind me to update dependecies when there is release

**Comment by d-biehl** [comment]
I think that would be good. 
but I would include the patch versions, so something like >=1.4,<1.7

**Comment by bhirsz** [comment]
I did setup dependabot and I have successfully updated all the packages,, except the rich_click which failed :) https://github.com/MarketSquare/robotframework-tidy/pull/518 But I have narrowed it down to 1.5.0 and code update which force different mode when it's running in the Github actions. No issue in the rich_click but this feature makes it unable to test it. I will need to workaround it first

**Comment by d-biehl** [comment]
Thanks!
