### ISSUE TITLE
ReplaceBreakContinue acting on Exit For Loop If adds extraneous string that breaks code

### ISSUE THREAD

**Issue by kylesower** [MarketSquare/robotframework-tidy#529]
file.robot:
`*** Keywords ***`
`Do Stuff`
`	@{strings} =  Create List  a very long string...........................................  not a very long string`
`	FOR  ${string}  IN  @{strings}`
`		Exit For Loop If  $string == 'a very long string...........................................'`
`	END`

Command:
`$ robotidy --line-length 80 file.robot`

Expected output:
`*** Keywords ***`
`Do Stuff`
`    @{strings} =    Create List`
`    ...    a very long string...........................................`
`    ...    not a very long string`
`    FOR    ${string}    IN    @{strings}`
`        IF    $string == 'a very long string...........................................'`
`            BREAK`
`        END`
`    END`

Actual output:
`*** Keywords ***`
`Do Stuff`
`    @{strings} =    Create List`
`    ...    a very long string...........................................`
`    ...    not a very long string`
`    FOR    ${string}    IN    @{strings}`
`        IF    $string == 'a very long string...........................................'`
`            BREAK...    $string == 'a very long string...........................................'`
`        END`
`    END`

**Comment by bhirsz** [comment]
Thanks for the report, I can reproduce it. I will fix it.

**Comment by bhirsz** [comment]
I've discovered it's combination of two transformers: ``SplitTooLongLines`` and ``ReplaceBreakContinue``. First one transforms to:

```
Exit For Loop If
    ...    $string == 'a very long string...................................................................'
```

and

then ``ReplaceBreakContinue`` transforms it to erroneus syntax. So the issue is that it does not handle multiline statements correctly.
