### ISSUE TITLE
Importing transformer 'AlignTestCases' failed

### ISSUE THREAD

**Issue by manosnoam** [MarketSquare/robotframework-tidy#530]
$ robotidy --version
robotidy, version 4.2.1

$ robotidy ods_ci/tasks/Resources/Provisioning/Hive
Error: Importing transformer 'AlignTestCases' failed. Verify if correct name or configuration was provided.

**Comment by bhirsz** [comment]
Hi, do you use any specific configuration? Or is there possible configuration file nearby that could be loaded automatically? I've tried to run it locally but it works. So it could be issue with the configuration (either the bug in Robotidy or invalid config etc)

**Comment by bhirsz** [comment]
Ah, I see that transformer is named ``AlignTestCasesSection`` and not ``AlignTestCases``. If you're using it somewhere in the configuration (with invalid name) it loads the configuration and then throws exception. Try to run it with ``--verbose`` flag, it should print where it reads the configuration from

**Comment by bhirsz** [comment]
I will assume that was the case and there was no issue - I will close the ticket. Please reopen it if the problem still persist and it's not because of the typo in the configuration.
