### ISSUE TITLE
RenameKeywords adds no space to replace underscore next to variable

### ISSUE THREAD

**Issue by ursa-h** [MarketSquare/robotframework-tidy#538]
When underscore removing is on, underscore next to variable is removed without adding space.
`Embedded ${variable}_And_Remove_Underscores`
becomes
`Embedded ${variable}And Remove Underscores`

Fixed in custom transformer by getting the padding character from function per input char and underscore setting, so that underscore triggers padding only when it is being removed.
To reduce complexity, function works on a char instead of the original string.endswith/startswith(). On the other hand this required more checks before the index operations to prevent out-of-range exceptions. 
Custom transformer skips quoted text instead of robot variables and leaves leading underscores in keyword names, so not usable as a fix as is.

    def padding(self, char):
        return " " if char == " " or (char == "_" and self.remove_underscores) else ""

**Comment by bhirsz** [comment]
Thanks for the report, I will take a look into it.

**Comment by bhirsz** [comment]
Fixed - it will be released in 4.4.0 today.
