### ISSUE TITLE
Disablers should be consistent with Robocop disablers

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-tidy#556]
Robotidy disablers:

```
# robotidy: off
# robotidy: on
```

Robocop disablers:

```
# robocop: disable
# robocop: disable=rule_name
# robocop: enable
```

It should use the same keywords. For backward compatiblity we can use both on/off/disable/enable keywords as equivalent:

```
# robotidy: disable
# robocop: off
```

**Comment by bhirsz** [comment]
I'm leaving towards leaving it as it is and only updating robocop to support on/off as a prefered way. That way we accustom people with it but don't introduce less preferred syntax (enable/disable) to robotidy.

**Comment by mnojek** [comment]
> I'm leaving towards leaving it as it is and only updating robocop to support on/off as a prefered way. That way we accustom people with it but don't introduce less preferred syntax (enable/disable) to robotidy.

Agreed. Better to use good practices as a foundation.

**Comment by bhirsz** [comment]
Closing the issue - Robotidy already supports on/off and Robocop now supports both (enable/disable for backward compatiblity and on/off from Robotidy). No work was needed since we have decided to not touch Robotidy and only modify Robocop.
