### ISSUE TITLE
robotidy --list output bug

### ISSUE THREAD

**Issue by szantotomi** [MarketSquare/robotframework-tidy#562]
..as per a former discussion in https://github.com/MarketSquare/robotframework-tidy/discussions/536

If I get it right, the robotidy --list command should print the enabled/disabled transformers based on the currently valid config (from my pyproject.toml file, for example.
If this is right, then there is some bug around :)
Thankfully, i've found in that other discussion that a complete config was linked, so that was used as a baseline (basically it's the same that i had before).
There, I've disabled a transformer by updating to "DiscardEmptySections:enabled=False"
Still, the output of robotidy --list shows this:
┏━━━━━━━━━━━━━━━
┃ Name ┃ Enabled ┃
┡━━━━━━━━━━━━━━
│ AddMissingEnd │ Yes │
│ NormalizeSeparators │ Yes │
│ DiscardEmptySections │ Yes │
...

However in fact, the transformer is really disabled as my "sandbox" code is not touched when robotidy is executed.

**Comment by bhirsz** [comment]
Thanks for noticing it. It actually worked correctly at some point - and our tests only check if the ``--list`` affected by configuration from cli. It looks like one of recent updates to configuration management, where robotidy does not read configuration just once but tries to find config for every source separately (allowing to keep several different configuration files in the repository) introduced this bug. 

To fix it, I will add a code that will try to find configuration file starting from current working directory if ``--list`` option was used.

**Comment by bhirsz** [comment]
As a workaround, pointing to configuration file manually works:

```
robotidy --config pyproject.toml --list
```
