### ISSUE TITLE
Keyword imported ok and unused imports when include keyword in "Wait Until Keyword Succeeds"

### ISSUE THREAD

**Issue by rubenss87** [MarketSquare/robotframework-tidy#571]
When a keyword of another file ".resource, .roboit" is used in another .robot file and it's included in the keyword "**Wait Until Keyword Succeeds**", as the next example:

_Wait Until Keyword Succeeds    ${timeout}    ${WUKS_DELAY}
    ...    KEYWORD INHERITED_
    
An error is reported:

_Keyword imported ok and unused imports:_

_actual_file **unused import:** source_file_

**Comment by bhirsz** [comment]
Hi, are you sure it's issue for robotidy and not the other tool? Could you present example what your code looked like before & after robotidy formatting and what you expect?

**Comment by rubenss87** [comment]
It's true, was a python script to check dependencies... A thousand apologies...
