### ISSUE TITLE
Robotidy should be more verbose

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-tidy#572]
When running default command:

```
robotidy .
```
or 
```
robotidy --check .
```

If nothing is formatted, nothing is printed - and it's not clear that anything actually was run. See black and isort output for example:

```
black --check .
10:51:22  All done! ✨ 🍰 ✨
10:51:22  35 files would be left unchanged.
isort --check .
10:51:23  Skipped 3 files
```

**Comment by bhirsz** [comment]
Example output
```
robotidy .
  3 files reformatted, 140 files left unchanged.
```

**Comment by ssallmen** [comment]
Robotidy does not tell about problems even when it detects some, when --check option is used. I woudl say that this is more of a bug than just enhancement.

**Comment by bhirsz** [comment]
What about combining - - check and - - diff, does that work?

**Comment by ssallmen** [comment]
Yes, with `--check --diff` I will get what robotidy would fix but that is not good enough. I think it should at least state that some files would need changes, or even which files would be modified like `black --check` does.

**Comment by ssallmen** [comment]
Thanks, it would be great!
