### ISSUE TITLE
[Transformer] Align Keywords and Test Cases sections

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-tidy#61]
Support column names for test templates.

**Comment by bhirsz** [comment]
I think I can partly develop it and then extend it later - since the topic here is quite broad. 

 I definietly want:
   - align templated tests (as it's done in old tidy)
   - align documentation in one column (similar how it's done in ``*** Settings ***``)
   
Aligning keywords and test cases itself will come later. For now the basic idea is to align code to columns, each block separetly:

```
*** Keywords ***
True examples
    Should Be Equal    ${xyz}    ${y}    Custom error    values=True         # Strings are generally true.
    Should Be Equal    ${x}    ${yyz}    Custom error    values=Yes   # Same as the above.
    FOR   ${var}  IN RANGE  10
        Log    stuff
        Keyword    ${var}
    END
```
to
```
*** Keywords ***
True examples
    Should Be Equal    ${xyz}    ${y}        Custom error    values=True         # Strings are generally true.
    Should Be Equal    ${x}        ${yyz}    Custom error    values=Yes          # Same as the above.
    FOR   ${var}  IN RANGE  10
        Log             stuff
        Keyword    ${var}
    END
```
One of the biggest challenges is figuring out how to deal with return values. They could be also aligned in column like appearance or ignored.
Aligning in column can also increase the length of the line - so even if SplitTooLongLine will split line, it will be made longer afterwards. Or if those transformers were to be executed in reverse order, if we first align then split then splitted lines will be misaligned. That's why we need some solution for running the same transformers few times in row until the code did not change. It could be availabe first through experimental flag like --recursive etc.

**Comment by bhirsz** [comment]
Partially implemented by #198

**Comment by bhirsz** [comment]
Restarting the topic!

There are several issues that needs to be covered - I will starting with FOR, WHILE, IF.. blocks.
Given this example (for the sake of the argument I'm assuming there is no max width for column specified, so every column will be aligned):
```
Keyword
    Keyword Call  ${arg}
    Keyword Call Longer  ${arg}  ${arg2}
    FOR    ${var}  IN   1  2
        Keyword Call  ${arg}
        Keyword Call Longer  ${arg}  ${arg2}
    END
    Keyword Call  ${arg}
    Keyword Call Longer  ${arg}  ${arg2}
```

We could align it as a whole, every statement and token compared to each other widths:
1)
```
Keyword
    Keyword Call                        ${arg}
    Keyword Call Longer                 ${arg}                 ${arg2}
    FOR                                 ${var}                 IN        1    2
                                        Keyword Call           ${arg}
                                        Keyword Call Longer    ${arg}    ${arg2}
    END
    Keyword Call With Even Longer Kw    ${arg}                 ${arg2}
    Keyword Call                        ${arg}
```
This looks ugly (imho) and I think we should rather align it "per block". And perhaps also skip aligning headers in FOR/IF etc?:
2)
```
Keyword
    Keyword Call                        ${arg}
    Keyword Call Longer                 ${arg}    ${arg2}
    FOR    ${var}    IN    1    2
        Keyword Call           ${arg}
        Keyword Call Longer    ${arg}    ${arg2}
    END
    Keyword Call With Even Longer Kw    ${arg}    ${arg2}
    Keyword Call                        ${arg}
```
Going even further we could align it "locally" (the "local cluster" would be all lines up to next block, so the lines after FOR are aligned to each other but not to the lines before "FOR"):
3)
```
Keyword
    Keyword Call           ${arg}
    Keyword Call Longer    ${arg}    ${arg2}
    FOR    ${var}    IN    1    2
        Keyword Call           ${arg}
        Keyword Call Longer    ${arg}    ${arg2}
    END
    Keyword Call With Even Longer Kw    ${arg}    ${arg2}
    Keyword Call                        ${arg}
```

Please comment what do you prefer - or you have any ideas for handling IF/FOR etc blocks.

**Comment by bhirsz** [comment]
Another topic: multiline statements.

Given:
```
Keyword    ${arg}
...    ${arg2}    {arg3}
Other Keyword    ${arg}
```
We could align in columns:
1)
```
Keyword          ${arg}
...              ${arg2}    {arg3}
Other Keyword    ${arg}
```
or skip formatting multilines (only align first line):
2)
```
Keyword          ${arg}
...    ${arg2}    {arg3}
Other Keyword    ${arg}
```

**Comment by bhirsz** [comment]
Aligning settings: Should we do it?

Given:
```
Keyword
    [Documentation]    This is doc
    [Arguments]     ${arg}    ${arg2}
    Keyword With Longer Name    2
    Shorter Keyword    1
```
I strongly believe we should not align documentation so I'm leaving it as is. If we were to align other settings:
1)
```
Keyword
    [Documentation]    This is doc
    [Arguments]                 ${arg}    ${arg2}
    Keyword With Longer Name    2
    Shorter Keyword             1
```
Without aligning settings:
2)
```
Keyword
    [Documentation]    This is doc
    [Arguments]     ${arg}    ${arg2}
    Keyword With Longer Name    2
    Shorter Keyword             1
```
I think 2) looks better and we shouldn't align settings in test case / keywords (templated test cases are separate topic). WDYT?

**Comment by bhirsz** [comment]
Very long lines:

There should be limit for aligning to width of the longest token in the column. For example:
```
Keyword
    Keyword Call    1
    Log    Quite long and verbose text about action being taken in this keyword    console=True
    Keyword Call    2
```
We don't want arguments ``1`` and ``2`` to be aligned with ``console=True`` - in this case Log keyword should be either entirely skipped or only columns that fit under max length should be aligned (whatever doesn't fit in column X, should be tried to be aligned with X + 1 column). This behaviour could be configurable.

**Comment by tkopra** [comment]
Excellent that this goes ahead! My comments for above open topics here:

FOR, WHILE, IF.. blocks
Option 2) is best by far, FOR etc. loops aligned separately from rest but not affecting normal rows. Headers with 4 spaces between without alignment to other columns.

Multiline statements:
By default alignment but it would be good to have also ability prevent that. (the perhaps separate exclusion functionality we discussed earlier, e.g. exclude starts_with  ...)

Aligning settings:
Maybe best to be skipped at the moment as less important topic and might need much configurability (e.g. Documentation: no, Arguments: yes., Tags: no) to fit all needs.  Is it worth implementing at least yet?

Very long lines:
Perhaps your example misses one argument for Keyword Call rows. Did you meant this?:
```
Keyword
    Keyword Call    arg1    arg2
    Log    Quite long and verbose text about action being taken in this keyword    console=True
    Keyword Call2   arg1    arg2
```

to
```
Keyword
    Keyword Call    arg1    arg2
    Log             Quite long and verbose text about action being taken in this keyword    console=True
    Keyword Call2   arg1    arg2
```

instead of
```
Keyword
    Keyword Call    arg1                                                                    arg2
    Log             Quite long and verbose text about action being taken in this keyword    console=True
    Keyword Call2   arg1                                                                    arg2
```

I vote for the second option "only columns that fit under max length should be aligned (whatever doesn't fit in column X, should be tried to be aligned with X + 1 column). This behaviour could be configurable."

**Comment by bhirsz** [comment]
Aligning settings doesn't cost any extra effort - but depending on #310 status I might first opt to not do them and add them after there is option to configure skipping particular types (skip:settings or more modular skip:settings:documentation,tags). Most likely it will be part of the same release though.

Very long lines: Yes you're right, I missed one extra argument. 

And extending on what we discussed separately: the goal is to have either fixed column widths or "align to the longest token in the column up to the configured maximum" (configurable between both). The first option would allow for more stability - so the alignment of the columns would not change easily. The second option would be better for people looking for more concise look.

**Comment by bhirsz** [comment]
Very long post ahead but I want to summarize the design so we don't lose anything:

We want to align test cases and keywords. Templated test cases should be covered by an existing AlignTestCases transformer (which should be renamed to AlignTemplatedTestCases). Keywords and Test Cases(or Tasks) should be covered by separate transformer (for easier configuring) but the logic of alignment should work the same for both section types.

Transformer should accept a list of the widths (40,30.20..). It will be used later in alignment logic (depending on the configuration). Missing widths should be supplied using the last width (so if you provide 50,40 but you need width for the third column, it will be also 40). The default column widths will be 40 (up to consideration). There will be possibility of configuring unlimited width (ie. set 0 to achieve it) -> it will work only for auto width mode and will always align token to the longest in the given column.

Tokens should be aligned into columns. Columns can be either fixed width or use the length of the longest token in the column. 
  Fixed width:
      Tokens shorter than column width should be aligned to width. For example if the token len is 20, desired width is 30 then the separator will be 10 char long. If it's not possible to fit a token and min. separator (default 4) under the desired width of the column the line will go in an "overflow" state (explained in the later part of the design). 
  Auto width:
      We check the lengths of the tokens in the given column. The longest token is used as reference to alignment (but no bigger than configured column width). For example: configured column width 30. Tokens in line1: 10, 15, 20. Tokens in line2: 15, 40, 10. The columns will be aligned using the following values: 15, 30, 20. If the token doesn't fit under the desired width of the column it will go in an "overflow" state. 

Overflow state:
   If the token doesn't fit in the column, we're in an "overflow" state. We can: ignore the line (just separate tokens using standard separator) or ignore the long token but try to align other columns in line. 

Alignment in the blocks (IF, WHILE, TRY..) should be done separately from the enclosing keyword/block. If the given block is in the middle of the keyword/test the lines before and after the block should be aligned to each other.

Alignment in the settings should be possible (skipping the documentation by default). Additonal feature #310 will cover the possibility of skipping given setting types.

Multiline statements should be aligned.

**Comment by bhirsz** [comment]
Memo for things to consider:
1. Inline IFs
