### ISSUE TITLE
RF7 is not recognized by --target-version

### ISSUE THREAD

**Issue by levlist** [MarketSquare/robotframework-tidy#620]
Hi,

currently the "rf7" is not available at the --target-version, although robotidy supports it.
When I tried to invoke robotidy with this way "**_... --target-version rf7_**" I got the following failure:

![rf7_invalid_value_from_cli](https://github.com/MarketSquare/robotframework-tidy/assets/10905822/ceb8ac8b-758f-446f-8a91-b8b23d863569)

If I tried from toml file I got this KeyError:

![rf7_KeyError_from_toml](https://github.com/MarketSquare/robotframework-tidy/assets/10905822/09d1989f-01a9-4cb1-b462-7292d23496ee)

Is it the planned behavior until the first RFW 7.0 stable version?

Thanks for your answer!

**Comment by bhirsz** [comment]
It's not planned, I forgot to add it. Thanks for report. Right now we dont
have any transformer specific for RF7 bu we will have (like replace set
variables with var).

pon., 8 sty 2024, 17:40 użytkownik levlist ***@***.***>
napisał:

**Comment by bhirsz** [comment]
Also you should got error message and not critical failure with error stack when configuring it in the toml - I will consider it as a bug.

**Comment by ChristopherJHart** [comment]
> Right now we dont have any transformer specific for RF7 bu we will have (like replace set variables with var).

Hi @bhirsz - can there be an issue opened to track this enhancement? We have a large Robot codebase that could benefit greatly from this, so we're very interested in a transformer that would automatically convert everything to using the new `VAR` statement.

**Comment by bhirsz** [comment]
Yeah sure @ChristopherJHart. Created #625. No promises but I will try to take a look into it in the close future.

**Comment by ChristopherJHart** [comment]
Thank you so much! Excellent project by the way, we're big fans 😅
