### ISSUE TITLE
skip_documentation argument does not work inside *** Settings *** section

### ISSUE THREAD

**Issue by levlist** [MarketSquare/robotframework-tidy#622]
Hi,

I tried the documented ways to skip documentation format in the *** Settings *** section but none of them worked.

- generic documentation skip from toml file:
```
   [tool.robotidy]
   skip-documentation = true
```
- transformer specific way from toml file:
```
   configure = [
        "AlignSettingsSection: skip_documentation=True"
   ]
```
- From CLI:
`robotidy --skip-documentation  <ROBOT_FILE> `

The results are the same in every case, all documentation lines were aligned.

Affected version: 4.8.0
Note: I did not try previous versions.

**Comment by bhirsz** [comment]
All the above skip options should work. Generally whenver we transform the code, we need to check if the code is not skipped manually (in the code). I see we don't do it for AlignSettingsSection. I would call it missing feature, thankfully easy to add. I will take care of it.
