### ISSUE TITLE
Relative glob resolved into an absolute path

### ISSUE THREAD

**Issue by MattCatz** [MarketSquare/robotframework-tidy#632]
The current interaction with `robotidy` and the `.gitignore` file can ignore the wrong files in certain situations.

If the absolute path of your working directory overlaps with a glob in your `.gitignore` then `robotidy` will ignore your entire project. This seems to happen because `pathlib.Path.resolve()` returns an absolute path.

For example, if your project is in `/tmp/a/b/c/d/my-project` and, your `.gitignore` include the glob `tmp/`, then `robotidy` will ignore your entire project.

I would expect the correct behavior to be only the folder `/tmp/a/b/c/d/my-project/tmp` being ignored by `robotidy`.

https://github.com/MarketSquare/robotframework-tidy/blame/776b2acb5b8387cd5486bfdcd376bc015717f149/robotidy/files.py#L128

**Comment by bhirsz** [comment]
I agree, we should parse gitignore paths relative to gitignore file location. Thanks for the report
