### ISSUE TITLE
Global variable changed to lower case in tags

### ISSUE THREAD

**Issue by gohierf** [MarketSquare/robotframework-tidy#638]
It seems that the rule [NormalizeTags](https://robotidy.readthedocs.io/en/stable/transformers/NormalizeTags.html) (I guess) wants all the tags in lower case. Which is fine, but should not apply to variable names inside tags.

Here is the code I would like to keep:
![before_robotidy](https://github.com/MarketSquare/robotframework-tidy/assets/33861657/adef9a06-51a0-409b-b1ff-929fd0b00318)

Here is the code I get after running robotidy:
![after_robotidy](https://github.com/MarketSquare/robotframework-tidy/assets/33861657/902b0e23-1a47-4f65-9778-41430f50b650)

**Comment by bhirsz** [comment]
I will consider it as a bug and fix it - by trying to autodiscover and ignore any possible variables in tags.

**Comment by bhirsz** [comment]
Also if the Robocop complains about tags not being lowercase (with variable) it will need separate issue in Robocop repo: https://github.com/MarketSquare/robotframework-robocop/issues . As Robocop tool discover and Robotidy fixes issues.

**Comment by bhirsz** [comment]
With the fix, variables are now ignored inside ``NormalizeTags``. I believe they should be formated with ``RenameVariables`` transformer - I will open issue for it.
