### ISSUE TITLE
Documentation is not updated to 4.10 version

### ISSUE THREAD

**Issue by Thibuko** [MarketSquare/robotframework-tidy#649]
When going to the documentation through link on main page when end up to https://robotidy.readthedocs.io/en/stable/ that still displays Robotidy 4.8.1 as stable.

Same issue in the release note for transform ReplaceWithVAR, the given [link](https://robotidy.readthedocs.io/en/stable/transformers/ReplaceWithVAR.html) give a 404 error

**Comment by bhirsz** [comment]
Thanks for issue, I see that read the docs now does not get webhooks without security tokens. And because of that our doc builds are not  triggered

**Comment by bhirsz** [comment]
Triggered it manually for now, I will fix integration later.

**Comment by Thibuko** [comment]
Good enough for me, thanks for the quick response. Needed the ReplaceWithVAR following your presentation this motning a Robcon, thanks for that also by the way ;)

**Comment by bhirsz** [comment]
I left thread open till the next (4.11.0) release to test if it works now - and it works now so I'm closing the issue.
