### ISSUE TITLE
[Bug] ReplaceWithVAR does detect empty separator as default separator (space)

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-tidy#651]
First of all, thanks for VAR transformer. It work great!

I found 1 issues

Keyword Catenate is converted incorrectly. It doesn't take the seperator attribuut into account.

old code:           ${dbUrl}  Catenate  SEPERATOR=  ${dbUrlPrefix}  :currentSchema=${schema} is converted to
converted code  VAR  ${dbUrl}  ${dbUrlPrefix}  :currentSchema=${schema}  SEPERATOR=${SPACE}

The old seperator meant, use NO seperator, and the converted code uses a space. This is different!

**Comment by bhirsz** [comment]
Thanks - I assumed incorectly that missing or empty separator equals ${SPACE}, whether it should recognize ``SEPERATOR=`` as ``SEPERATOR=${EMPTY}`` and only no separator at all should yield defau;lt ``${SPACE}``.
