### ISSUE TITLE
[Bug] AlignTemplatedTestCases not working with test case `[Template]` setting

### ISSUE THREAD

**Issue by gohierf** [MarketSquare/robotframework-tidy#657]
[AlignTemplatedTestCases](https://robotidy.readthedocs.io/en/stable/transformers/AlignTemplatedTestCases.html) works when defining a unique template for the whole suite file in `Test Template` suite setting, but not when using the test case `[Template]` setting.

In the example below I have to disable robotidy or my arguments alignment is transformed to the default 4 spaces.

```robot
*** Test Cases ***    # robotidy: off
Testing Random List
    [Template]    Validate Random List Selection
    # collection          nbr items
    ${HOMOGENOUS LIST}    2
    ${MIXED LIST}         3
    ${NESTED LIST}        4
    ${HOMOGENOUS LIST}    10
    ${MIXED LIST}         11
    ${NESTED LIST}        12

Testing Random Item
    [Template]    Validate Random Item Selection
    # collection
    ${HOMOGENOUS LIST}
    ${MIXED LIST}
    ${NESTED LIST}

Testing Random Dict
    [Template]    Validate Random Dict Selection
    # collection          nbr items
    ${HOMOGENOUS DICT}    2
    ${MIXED DICT}         3
    ${NESTED DICT}        4
    ${HOMOGENOUS DICT}    10
    ${MIXED DICT}         11
    ${NESTED DICT}        12

Testing Random Sleep
    [Template]    Validate Random Sleep Duration
    # max expected    min delay    add delay
    1.1s              1s           ${EMPTY}    # Default Add Delay
    1.2s              1s           20%         # Percentage Add Delay
    2s                1s           100%        # Percentage Limits
    2.2s              1s           120%        # Percentage Overlimit
    1.1s              1.0          1e-1        # Number Format
    1.1s              1s           100ms       # Time Format
    1.1s              1000ms       0.1         # Mixed Format
    1s                1s           0           # Zero additional Delay
    1s                1s           0%          # Zero Percent

Testing Random Number
    [Template]    Validate Random Integer/Number Choice
    # method    min                 max
    number      30e-10              5.26                # positive
    number      26e3                15                  # positive max under min
    number      -18e0                -2.2E0             # negative
    number      -26                 -28                 # negative max under min
    number      ${{ - math.pi }}    ${{ math.e }}       # mixed
    number      ${{ math.e }}       ${{ -math.tau }}    # mixed max under min
    number      5.0                 5                   # no range

Testing Random Integer
    [Template]    Validate Random Integer/Number Choice
    # method    min      max
    integer    198564    265489865    # positive
    integer    3221564   325          # positive max under min
    integer    -231      -10          # negative
    integer    -2        -212         # negative max under min
    integer    -56       56           # mixed
    integer    23        -15          # mixed max under min
    integer    -2        -2           # no range
```

Note that `AlignTemplatedTestCases` makes it possible to align with named header. But for the `[Template]` setting, [it is not mentioned that there is a way to define named header](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-templates). So probably only `Fixed width of column` would be available.

**Comment by bhirsz** [comment]
Suprisingly we don't support formatting tests with ``[Template]`` (suprisingly since there is a lot of code to handle normal test cases and templated with Test Template). I need to think what would be the best transformer to format such code. Going by name itself ``AlignTemplatedTestCases`` would be best but ``AlignTestCasesSection`` would produce code closer to what we want. I will think about it and add missing support for ``[Template]`` tests.

**Comment by bhirsz** [comment]
Also we don't align comments. I have added aligned ``[Template]`` locally but comments looks like:

```
Testing Random Sleep
    [Template]    Validate Random Sleep Duration
    # max expected    min delay    add delay
    1.1s                    1s                      ${EMPTY}  # Default Add Delay
    1.2s                    1s                      20%  # Percentage Add Delay
    2s                      1s                      100%  # Percentage Limits
    2.2s                    1s                      120%  # Percentage Overlimit
    1.1s                    1.0                     1e-1  # Number Format
    1.1s                    1s                      100ms  # Time Format
    1.1s                    1000ms                  0.1  # Mixed Format
    1s                      1s                      0  # Zero additional Delay
    1s                      1s                      0%  # Zero Percent
    ```
    
    it may be personal preference so I will maybe add flag to recognize comments as tokens to be aligned.

**Comment by gohierf** [comment]
Are you talking about the "header" comments (on the first line of the tests case) or the "test name" comments (and the end of each line)?

If both were supported, it would be awesome.

**Comment by bhirsz** [comment]
Test name comments. I was able to support them - changes are done in my branch. But I will need to test it, document so it will not go in the next release. Code changes are done though so it shouldn't be long anyway.

**Comment by gohierf** [comment]
If I add the following configuration, then headers "standalone" comments keep my arbitrary number of spaces.
Hopefully, this setting would not disable the alignment of test name comments?

```toml
[tool.robotidy]
configure = [
    "NormalizeSeparators : skip_comments = True"
]
```

**Comment by bhirsz** [comment]
I would need to check but I don't think so - I will include that in our tests to make sure.

**Comment by bhirsz** [comment]
Also --skip-comments like other --skip can be global and transformer level. In your configuration it's transformer level only (for NormalizeSeparators). That's why it will not affect Align* transformers for sure. I will only check how it behaves with global --skip-comments.

**Comment by bhirsz** [comment]
The status is that I forget about how advanced the change was. I will look into it so it will get it to the next release. The simples workaround would be disabling transformer fully.

**Comment by jyligehc** [comment]
I mean that even not having that transformer enable (AlignTemplatedTestCases) (the default situation) I get the above formatting.
So maybe some other transformer is doing that.
There seems to be some reordering of the Test Case section settings.

**Comment by bhirsz** [comment]
``[Template]`` is aligned by ``AlignTestCases`` transformer, ``AlignTemplatedTestCases`` only handles suites with ``Test Template``

**Comment by bhirsz** [comment]
And this behaviour will stay after my update not not mess too much with the code, but I will update that ``[Template]`` is aligned properly

**Comment by bhirsz** [comment]
Linked PR with the change. I will make release right after merging it (should be in a day). It is now possible to achieve all formats listed in this discussion, however you may need to configure transformers a bit. For example to also align comments or align settings separately from template arguments. Release notes should contain all required information
