### ISSUE TITLE
[Enhancement] Normalize EOL symbols in file

### ISSUE THREAD

**Issue by Cavaler** [MarketSquare/robotframework-tidy#668]
Currently (4.10.0) EOL symbols in output are operating system-dependent, which can clash with git checkout settings for example.

It would be nice to have an option to force them to be LF (Unix-style) or CRLF (Windows-style) manually.

**Comment by bhirsz** [comment]
What about lineseparator option?

https://robotidy.readthedocs.io/en/stable/quickstart.html#line-endings

By default it uses native system eol but it can be switched to auto detect or overwrite with specific.
