### ISSUE TITLE
[bug] SplitTooLongLine removes all but first returned value 

### ISSUE THREAD

**Issue by adrszad** [MarketSquare/robotframework-tidy#68]
Consider line:
${var1}    ${var2}    Some Lengthy Keyword So That This Line Is To Long   ${arg1}   ${arg2}

it's transformed to:
${var1}   Some Lengthy Keyword So That This Line Is To Long
...       ${arg1}   ${arg2}

**Comment by bhirsz** [comment]
Thanks for the report. I've tested it and I can also confirm this bug. I will take a look into fixing it. While working at it I will also consider problems with long variable names.

**Comment by bhirsz** [comment]
Fixed in #72. I've created separate issue for splitting on too long assignment variable names.
