### ISSUE TITLE
Add option to disable variable_separator in RenameVariables transformer.

### ISSUE THREAD

**Issue by fialsha** [MarketSquare/robotframework-tidy#682]
**Enhancement request**: add option to disable `variable_separator` in `RenameVariables` transformer.

Currently, `RenameVariables:variable_separator` can only be configured to underscore or space. 
We would like to disable it completely, but still use rest of the capabilities of `RenameVariables` transformer.
Something like:  
```
robotidy -c RenameVariables:variable_separator=False
```

_Use case_ 
We use variables in the following format to represent nested values in YAML files:
```
MY_VAR__NESTED_VAR_1__NESTED_VAR_2
```
The `RenameVariables:variable_separator` transformer interferes with these variables.

**Comment by bhirsz** [comment]
I've looked in the source code and it looks doable. We always convert to one format and then either to space or underscore but I can add option to not convert at all. Since the parameter is str (underscore / space) I would add third value (ie "ignore")
