### ISSUE TITLE
Make --list-transformers output ordered

### ISSUE THREAD

**Issue by adrszad** [MarketSquare/robotframework-tidy#69]
Use case:
when applying rules one by one it seems to be more convenient to have this list ordered to better see what's left, instead of having it shuffled. Also for some automated workflows ordered list would be better.

**Comment by bhirsz** [comment]
When I think about it - we are defing our transformers as (frozen) set. It's actually problem because I can't ensure that it will run transformers in "proper" order (ie. first remove empty section then normalzie new lines). I will change that to list. It should complete this issue as well.

**Comment by bhirsz** [comment]
Default order will be the order the transformers are run
