### ISSUE TITLE
Missing new keyword 'setup' setting in OrderSettings transformer

### ISSUE THREAD

**Issue by gohierf** [MarketSquare/robotframework-tidy#690]
[Since RF 7.0, keywords now accept a `setup` argument.](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#settings-in-the-keyword-section)

This is not yet supported by robotidy [OrderSettings ](https://robotidy.readthedocs.io/en/stable/transformers/OrderSettings.html)transformer and result in the following error:

    Error: OrderSettings: Invalid 'keyword_before' parameter value: 'arguments,documentation,tags,timeout,setup'. Custom order should be provided in comma separated list with valid setting names: arguments,documentation,return,tags,teardown,timeout

### Side note, regarding documentation
While we are on the subject of OrderSettings transformers, I found that the documentation is lacking the following:
- the first before/after example only shows "keyword" reordering. It would be nice to add a "testcase" to it for completeness. 
- the second before/after example could also show both "testcase" and "keyword", to highlight that default `keyword_before` and `keyword_after` were not modified when configuring `test_before` and `test_after`. Although this can be deduced by reading the current documentation carefully, adding it in the example might help to find this out.
- finally, it is not quite clear that it is possible to configure `keyword_before`, `keyword_after`,  `test_before`, and `test_after`, in separate CLI/toml configuration calls. It was not obvious to me.
 
### Another side note, regarding robotcode
My need to put the `arguments` setting first originated from a [current limitation in robotcode](https://github.com/robotcodedev/robotcode/issues/240). Maybe you have some information to share on the topic?

**Comment by bhirsz** [comment]
1) Thanks for pointing it out, it will be fixed

2) And thanks for all notes for documentation - it's really helpfull as the tool is only as good as its documentation, with missing bits it would be not used :) 

3) Looking into it, I believe the timeout default order should be moved. Ideally after arguments since it can have variables from arguments (which btw may not be supported by robotidy/robocop variable rules/transformers)

**Comment by bhirsz** [comment]
Style guide already propose (based on User Guide) a bit better order:

https://docs.robotframework.org/docs/style_guide#settings

I've also checked - [Tags] and [Documentation] can't use values from arguments, only from global variables. [Timeout], [Setup] and [Teardown] can use [Arguments]. Hence proposed order will work best.

Test code I used for debugging:

```
*** Variables ***
${global}    global


*** Test Cases ***
Test
    Dynamic Tag    smoke    1

Test 2
    Dynamic Tag    regression    2


*** Keywords ***
Dynamic Tag
    [Arguments]    ${arg}   ${arg2}
    [Documentation]    Doc with ${arg} and ${global}
    [Tags]    my-${arg}
    [Timeout]    ${arg2} min
    Log    ${arg}
```
