### ISSUE TITLE
[Transformer]  Fix sections order

### ISSUE THREAD

**Issue by adrszad** [MarketSquare/robotframework-tidy#70]
Fix sections order. 
This could also support merging sections if they're defined more than once in a file, e.g.:

***  Keywords ***
Keyword 1  
*** Test Cases ***
Test 1
*** Keywords ***
Keyword 2

Should be changed to: 

*** Test Cases ***
Test 1
*** Keywords ***
Keyword 1
Keyword 2

**Comment by bhirsz** [comment]
Good idea :) I will take a shot into implementing this.

**Comment by bhirsz** [comment]
Thought: there could be different method of naming the section (*** Keyowrd *** vs *** Keywords *** vs ***keyword*). When merging I will just pick first encountered name. This name should be normalized by ``NormalizeSectionHeaderName`` later on.

**Comment by bhirsz** [comment]
Also linesb before first section are comments, so it should go to ``***Comments *** section:

```
some general comment

*** Settings ***
Library   Stuff
```
to
```
*** Comments ***
some general comment

*** Settings ***
Library   Stuff
```

**Comment by bhirsz** [comment]
Additional note: I will also need to handle possible comments:
```
*** Test Case ***  i am comment
*** Test Case ***
*** Test Cases ***  yet again so comment   and here
```

There are following ways to deal with them:
1) just remove them but print the warning message
2) merge them
3) merge unique ones
4) keep only first encountered and warn on the rest

It could be also possible to use parameter so others can decide what they're doing with section comments.

**Comment by bhirsz** [comment]
I linked WIP PR. Regarding last comment I went with 4) (I'm keeping only the header comments from the first section of the same type).
