### ISSUE TITLE
[Enhancement] Add transformer to address Robocop's builtin-imports-not-sorted rule

### ISSUE THREAD

**Issue by ChristopherJHart** [MarketSquare/robotframework-tidy#706]
We have a large Robot Framework codebase that has a lot of violations against [Robocop's builtin-imports-not-sorted rule](https://robocop.readthedocs.io/en/stable/rules_list.html#builtin-imports-not-sorted-w0926) that was added early last June. It would be *really* nice if there was a transformer that automatically sorted built-in imports to enforce compliance with this rule.

**Comment by bhirsz** [comment]
Agreed. Potentially we should enhance OrderSettingsSecrion with this functionality.

**Comment by bhirsz** [comment]
I've checked the code and I see the feature I have forgotten about in https://robotidy.readthedocs.io/en/stable/transformers/OrderSettingsSection.html . Theoretically if you configure OrderSettingsSection with imports_order it should also order built-ins (place them on top and sort alphabetically). Can you confirm it works for you? @ChristopherJHart

**Comment by ChristopherJHart** [comment]
@bhirsz Oh very nice, I didn't know there was a transformer that did this already! I tested it and can confirm it worked (and just saved us a *ton* of work). Thank you so much!
