### ISSUE TITLE
"Library and Resources" against the style guide

### ISSUE THREAD

**Issue by jannekSympa** [MarketSquare/robotframework-tidy#723]
As a robot style guide: https://docs.robotframework.org/docs/style_guide#settings

in the `*** Settings ***` section says libraries should be before resources like:
```
*** Settings ***
Documentation
Metadata

Library    BuiltIn
Library    3rd Party
Library    Custom
Resource
Variables
```

If we have example robot file
```
*** Settings ***
Documentation       Test for robotidy section example.

Resource            ./test.resource


Suite Setup         Suite Setup

Library             Collections
```

after `robotidy test.robot`

```
*** Settings ***
Documentation       Test for robotidy section example.

Resource            ./test.resource
Library             Collections

Suite Setup         Suite Setup
```

Library is after Resource

robotidy, version 4.14.0
Robot Framework 6.1.1 (Python 3.12.8 on win32)

**Comment by bhirsz** [comment]
Import order in ``*** Settings ***`` is by default preserved:

https://robotidy.readthedocs.io/en/stable/transformers/OrderSettingsSection.html

The reason behind it is that it would be potentially breaking change, as a lot of projects depend on the import order (ie library uses resource from imported resource in the same file). In long run I want to create similiar rule (if not already present, I need to check) in Robocop that will offer 'unsafe fix'.

If you know that your code doesn't depend on the import order, you can configure ``imports_order`` parameter. For example to ``library,resource,variables``
