### ISSUE TITLE
[Transformer] Remove settings without values

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-tidy#78]
Settings without values should be removed:

```
*** Settings ***
Test Template

*** Keywords ***
Keyword
    [Arguments]    
    Keyword2
```

**Comment by adrszad** [comment]
please consider empty teardown/setup used to overwrite suite teardown/setup, maybe it could be paramterize to remove it or to add 'No Operation'?

**Comment by bhirsz** [comment]
@adrszad yeah I was thinking about it - I can add parametr to cover such cases (same for timeout, tags overwriting default tags etc)

**Comment by bhirsz** [comment]
It could also auto detect if there is suite teardown/setup set at all - without it we could remove empty settings anyway
